backend/src/services/kanban/Jira/Jira.ts
backend/tests/fixture/EmptySprints.json
backend/tests/fixture/Sprints.json
backend/tests/services/kanban/Jira/Jira.test.ts

https://dorametrics.atlassian.net/browse/ADM-218

[ADM-218] Get all sprints data from API

---

backend/package.json
backend/src/services/GenerateReporter/GenerateSprintReporterService.ts
backend/tests/fixture/JiraCards.json
backend/tests/services/GenerateKanbanReporter/GenerateSprintReporterService.test.ts
backend/tests/services/kanban/Jira/Jira.test.ts

https://dorametrics.atlassian.net/browse/ADM-209

[ADM-209] Calculate blocked percentage and development percentage

---

backend/src/contract/kanban/KanbanStoryPointResponse.ts
backend/src/services/GenerateReporter/GenerateSprintReporterService.ts
backend/tests/fixture/Sprints.json
backend/tests/services/GenerateKanbanReporter/GenerateSprintReporterService.test.ts
backend/tests/services/GenerateSprintReporterService/GenerateSprintReporterService.test.ts
backend/tests/services/kanban/Classification.test.ts
backend/tests/services/kanban/Jira/Jira.test.ts

https://dorametrics.atlassian.net/browse/ADM-208

[ADM-208] Calculate the standard deviation(population) of cycle time(days)

---

backend/src/contract/kanban/KanbanStoryPointResponse.ts
backend/src/services/GenerateReporter/GenerateSprintReporterService.ts
backend/tests/services/GenerateReporter/GenerateSprintReporterService.test.ts

https://dorametrics.atlassian.net/browse/ADM-222

[ADM-222] calculate the completed cards number in every sprint

---

frontend/src/app/dora/components/index.ts
frontend/src/app/dora/components/reports/average-cycle-time/average-cycle-time.component.html
frontend/src/app/dora/components/reports/average-cycle-time/average-cycle-time.component.scss
frontend/src/app/dora/components/reports/average-cycle-time/average-cycle-time.component.ts
frontend/src/app/dora/components/reports/block-reason-percentage/block-reason-percentage.component.html
frontend/src/app/dora/components/reports/block-reason-percentage/block-reason-percentage.component.scss
frontend/src/app/dora/components/reports/block-reason-percentage/block-reason-percentage.component.ts
frontend/src/app/dora/components/reports/reports.component.html
frontend/src/app/dora/components/reports/throughput/throughput.component.html
frontend/src/app/dora/components/reports/throughput/throughput.component.scss
frontend/src/app/dora/components/reports/throughput/throughput.component.ts
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.html
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.scss
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.ts

[ADM-223](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-223)
because we will working on the front-end, and will modify some common file, so in order to avoid conflict, we doing some basic work, modify the common file at first.
Folder name are `block-reason-percentage`, `average-cycle-time`, `time-allocation`, `throughput`
Create file for every folder  which will contain for file (html, css, spec.ts, ts), and add common code for html ts and css part

ADM-223: Complete basic part in front-end

---

frontend/src/app/dora/components/reports/reports.component.html
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.html
frontend/src/app/dora/types/reportResponse.ts

1. Update ReportResponse and add new items.
2. Modify sequence about different component

ADM-223:Update ReportResponse and add new items.

---

backend/src/contract/GenerateReporter/GenerateReporterResponse.ts
backend/src/models/kanban/SprintStatistics.ts
backend/src/services/GenerateReporter/GenerateReportService.ts
backend/src/services/GenerateReporter/GenerateSprintReporterService.ts
backend/tests/services/GenerateReporter/GenerateSprintReporterService.test.ts

**Jira**
https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-214

ADM-214 Export the board data as an excel file

---

frontend/package.json
frontend/src/app/dora/components/reports/block-reason-percentage/block-reason-percentage.component.spec.ts
frontend/src/app/dora/components/reports/block-reason-percentage/block-reason-percentage.component.ts
frontend/src/app/dora/components/reports/reports.component.html

[ADM-211](https://dorametrics.atlassian.net/browse/ADM-211)
because we want to  know the differences among the block reasons and I could make improvement in the future.
1. block-reason-percentage.component.spec.ts
2. block-reason-percentage.component.ts

ADM-211: Draw graph of block reason for the latest iteration

---

frontend/src/app/dora/components/reports/average-cycle-time/average-cycle-time.component.spec.ts
frontend/src/app/dora/components/reports/average-cycle-time/average-cycle-time.component.ts
frontend/src/app/dora/components/reports/reports.component.html

**Jira**
https://dorametrics.atlassian.net/browse/ADM-206

[ADM-206]Draw graph of average cycle time

---

frontend/package.json
frontend/src/app/dora/components/reports/reports.component.html
frontend/src/app/dora/components/reports/throughput/throughput.component.spec.ts
frontend/src/app/dora/components/reports/throughput/throughput.component.ts

https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-205

ADM-205 Draw graph related to throughput

---

frontend/src/app/dora/components/reports/reports.component.html
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.spec.ts
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.ts

[ADM-210](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-210)

ADM-210: Draw graph of time allocation

---

frontend/src/app/dora/components/reports/average-cycle-time/average-cycle-time.component.scss
frontend/src/app/dora/components/reports/average-cycle-time/average-cycle-time.component.ts
frontend/src/app/dora/components/reports/throughput/throughput.component.scss
frontend/src/app/dora/components/reports/throughput/throughput.component.ts
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.scss
frontend/src/app/dora/components/reports/time-allocation/time-allocation.component.ts

**Jira**
https://dorametrics.atlassian.net/browse/ADM-228

[ADM-228]Make the front-end graphs style consistent

---

backend/package.json
frontend/angular.json
frontend/karma.conf.js

[ADM-229](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-229)

ADM-229 update config

---

backend/src/services/GenerateReporter/GenerateSprintReporterService.ts
backend/tests/services/GenerateReporter/GenerateSprintReporterService.test.ts

[ADM-233](https://dorametrics.atlassian.net/browse/ADM-233)

ADM-233 Complementary test in GenerateSprintReporterService.ts

---

backend/src/models/kanban/SprintStatistics.ts
backend/src/services/GenerateReporter/GenerateSprintReporterService.ts

https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-235
https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-237

[ADM-235][ADM-237] Modify inappropriate name of function or field

---

backend/.gitignore
backend/src/models/kanban/SprintStatistics.ts
backend/src/services/GenerateReporter/GenerateSprintReporterService.ts

https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-235

ADM-237-fix Modify inappropriate name of function or field

---

backend/tests/fixture/ColumnResponse.json
backend/tests/fixture/NonDoneJiraCard.json
backend/tests/fixture/NonDoneJiraCardCycleTime.json
backend/tests/fixture/StatusData.json
backend/tests/fixture/statuses/ReadyForPickUpStatus.json
backend/tests/services/kanban/Jira/Jira.test.ts

**Jira**
https://dorametrics.atlassian.net/browse/ADM-234

[ADM-234]Complementary test in Jira.ts file

---

frontend/src/app/dora/dora-routing.module.ts

[ADM-225](https://dorametrics.atlassian.net/browse/ADM-225)

ADM-225 Homepage redirect issue

---

frontend/src/app/dora/components/reports/throughput/throughput.component.ts

[ADM-242](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-242)

[ADM-242] Fix the trend line for Throughput chart

---

backend/src/errorHandler.ts
backend/src/services/kanban/Jira/JiraVerifyToken.ts
backend/src/services/kanban/Linear/Linear.ts
backend/src/services/kanban/Linear/LinearVerifyToken.ts
backend/src/types/NoCardsInDoneColumnError.ts
backend/src/types/SpringStatisticsError.ts
backend/src/types/SprintStatisticsError.ts

[ADM-238](https://dorametrics.atlassian.net/browse/ADM-238)

ADM-238 Collect exceptions and handle them centrally

---

backend/src/services/GenerateReporter/GenerateReportService.ts
backend/tests/services/GenerateReporter/GenerateReportService.test.ts

https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-232

Adm 232-Complementary test in GenerateReportService.ts file

---

backend/tests/services/GenerateReporter/GenerateReportService.test.ts

https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-232

ADM-232 refactor  GenerateReportService file

---

backend/package.json
backend/src/services/common/GeneraterCsvFile.ts
backend/src/services/common/WorkDayCalculate.ts
backend/tests/controller/GenerateReportController.test.ts
backend/tests/services/GenerateReporter/GenerateReportService.test.ts
backend/tests/services/kanban/Jira/Jira.test.ts
backend/tests/services/kanban/Linear/Linear.test.ts
backend/tests/services/kanban/util.test.ts

[245](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-245)

ADM-245: Replace require statement by import statement in backend

---

frontend/src/app/dora/components/config-stepper/metrics/metrics-board/done-columns/done-columns.component.ts
frontend/src/app/dora/components/config-stepper/reports/average-cycle-time/average-cycle-time.component.ts
frontend/src/app/dora/service/api.service.spec.ts
frontend/src/app/dora/service/api.service.ts
frontend/src/app/dora/service/cycle-done.service.spec.ts
frontend/src/app/dora/service/cycle-done.service.ts
frontend/src/app/dora/service/import-config.service.spec.ts
frontend/src/app/dora/types/JiraBoardParam.ts
frontend/src/app/dora/types/LinearBoardParam.ts

[ADM-259](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-259)

Adm 259 Increase the test coverage for api & import-config & cycle-done service file in frontend

---

frontend/package.json
frontend/src/app/dora/components/config-stepper/reports/throughput/throughput.component.ts

- Fix trend line calculate method
- Add pre-push hook in frontend

[ADM-242] Fix trend line in throughput figure.

---

frontend/src/app/dora/components/config-stepper/reports/reports.component.spec.ts
frontend/src/app/dora/components/config-stepper/reports/reports.component.ts

[ADM-241](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-241)

ADM 241 Complementary test in reports.component.ts file

---

frontend/package.json

- Revert git hooks to fix push code issue.

Revert git hooks.

---

frontend/src/app/dora/models/boardParams.spec.ts
frontend/src/app/dora/models/codebaseParams.spec.ts
frontend/src/app/dora/models/pipelineParams.spec.ts
frontend/src/app/dora/models/reportParams.spec.ts

https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-265

ADM-265: increase test coverage for models file in frontend

---

backend/tests/services/codebase/GitHub.test.ts

- add test for fetchCommitInfo in GitHub.

[ADM-261] Add test for fetchCommitInfo in GitHub service.

---

backend/src/services/GenerateReporter/GenerateReportService.ts
backend/src/services/common/GeneraterCsvFile.ts
backend/tests/services/GenerateReporter/GenerateReportService.test.ts

[ADM-249](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-249)

ADM-249:make csv a sheet of excel 

---

backend/src/services/pipeline/Buildkite/Buildkite.ts
backend/tests/services/pipeline/Buildkite.test.ts

[ADM-266](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-266)

ADM-266 shorten time for verifying pipeline

---

backend/src/controller/PipelineController.ts
backend/src/services/pipeline/Buildkite/Buildkite.ts
backend/src/services/pipeline/Buildkite/BuildkiteGetSteps.ts
backend/src/services/pipeline/PipelineGetSteps.ts
backend/src/types/FetchParams.ts
backend/tests/services/pipeline/Buildkite.test.ts
backend/tests/services/pipeline/BuildkiteGetSteps.test.ts
backend/tests/services/pipeline/PipelineGetSteps.test.ts

[ADM-271](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-271)

ADM-271 Shorten time for fetching pipeline steps

---

backend/src/contract/GenerateReporter/GenerateReporterRequestBody.ts
backend/src/contract/GenerateReporter/GenerateReporterResponse.ts
backend/src/models/RequireDataEnum.ts
backend/src/services/GenerateReporter/GenerateReportService.ts
backend/tests/services/GenerateReporter/GenerateReportService.test.ts
frontend/src/app/dora/components/config-stepper/reports/reports.component.html
frontend/src/app/dora/components/config-stepper/reports/secondary-metrics/secondary-metrics.component.ts
frontend/src/app/dora/types/reportResponse.ts
frontend/src/app/dora/utils/config.ts

**Jira**
https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-246

ADM-246: add a new option secondary metrics in Required Data dropdown

---

backend/tests/services/common/GeneraterCsvFile.test.ts

[ADM-276](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-276)

ADM-276:increase test coverage for GeneraterCsvFile in backend

---

backend/src/services/GenerateReporter/GenerateReportService.ts
backend/src/services/pipeline/Buildkite/Buildkite.ts
backend/src/services/pipeline/Pipeline.ts

- Refactor generateCsvForPipeline methods
- Refactor fetchOriginalData
- Refactor fetchDataFromPipeline and fetchDataFromCodebase

[ADM-272] Refactor pipeline part of generating report to shorten time

---

.github/workflows/Create and publish a image.yml
.github/workflows/backend.yml
.github/workflows/frontend.yml
.github/workflows/image.yml
backend/Dockerfile
backend/package.json

_Null_
Verify building package and image are workable
_Null_

chore: Build and push image

---

.github/workflows/backend.yml
backend/.gitignore
backend/package.json
backend/src/server.ts
backend/src/services/kanban/Jira/Jira.ts
backend/src/services/kanban/Jira/JiraVerifyToken.ts
backend/src/utils/loggerUtils.ts
backend/tests/services/kanban/Linear/Linear.test.ts
backend/tests/utils/loggerUtils.test.ts
backend/yarn.lock

- Uniform log
```sh
Successfully queried status_data
```
- No test report
- Covert `console` to `logger`
- Add test coverage report
_Null_

chore: use log4js to do logging and test report

---

infra/Dockerfile.backend
infra/Dockerfile.frontend

_Description_
_Description_
_Null_

fix: Fix label of dockerfile

---

.github/workflows/Deploy.yml

_Description_
_Description_
_Null_

fix: Delete ssh lead path

---

.github/workflows/BuildAndDeploy.yml
infra/docker-compose.yml

_Description_
_Description_
_Null_

fix: fix deploy

---

backend/README.md
backend/build.gradle

./gradlew test no info out put
./gradlew test with test info run by this command in console

ADM-338 add log for gradle test

---

.github/workflows/backend.yml
.github/workflows/frontend.yml
backend/build.gradle

No static code check in pipeline, cannot block code smell.
Add Codacy for  static code check and PR will be blocked when code smell is contained.
_Null_

ADM-311 upload test report to codacy in github action

---

backend/src/constants.ts
backend/src/services/codebase/GitHub.ts
backend/src/services/common/GeneraterCsvFile.ts
backend/src/services/kanban/Jira/Jira.ts
backend/src/services/kanban/Jira/JiraVerifyToken.ts
backend/src/services/pipeline/Buildkite.ts
backend/src/services/pipeline/Buildkite/BuildkiteGetSteps.ts
backend/src/utils/responseLoggerUtils.ts

In order to mock JIRA/Buildkite/Github, we have to get the real data from production. We need to be able to log those response.
Add logs for Jira request and response
Add logs for BuildKite request and response
Add logs for Github request and response
Need add log to capture response from JIRA/Buildkite/Github

ADM-342 Add log to capture response from JIRA/Buildkite/Github

---

frontend/e2e/src/pages/metrics.test.ts

fix e2e error
[e2e error](locator.click: Target closed)
e2e pass

ADM-358 fix e2e test

---

frontend/e2e/src/pages/Metrics.ts
frontend/e2e/src/tests/metrics.spec.ts

ADM-358 fix test assertion

---

frontend/__tests__/src/client/PipelineToolClient.test.ts
frontend/__tests__/src/components/metrics/ConfigStep/MetricsTypeCheckbox.test.tsx
frontend/__tests__/src/components/metrics/ConfigStep/PipelineTool.test.tsx
frontend/__tests__/src/features/configSlice.test.tsx
frontend/__tests__/src/features/pipelineToolSlice.test.tsx
frontend/__tests__/src/features/pipelineToolVerifyResponseSlice.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/useVerifyPipelineToolEffect.test.tsx
frontend/__tests__/src/utils/setupStoreUtil.tsx
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics.ts
frontend/src/clients/PipelineToolClient.ts
frontend/src/components/Metrics/ConfigStep/MetricsTypeCheckbox/index.tsx
frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx
frontend/src/components/Metrics/ConfigStep/PipelineTool/style.tsx
frontend/src/constants.ts
frontend/src/features/config/configSlice.tsx
frontend/src/features/pipelineTool/pipelineToolSlice.tsx
frontend/src/features/pipelineToolVerifyResponse/pipelineToolVerifyResponseSlice.tsx
frontend/src/hooks/useVerifyPipelineToolEffect.ts
frontend/src/store.ts

...
_Description_
_Description_
_Null_

ADM-350 PipelineTool Selection

---

backend/src/main/java/heartbeat/client/GithubFeignClient.java
backend/src/main/java/heartbeat/client/dto/GithubOrgsInfo.java
backend/src/main/java/heartbeat/client/dto/GithubRepos.java
backend/src/main/java/heartbeat/controller/source/GithubController.java
backend/src/main/java/heartbeat/controller/source/vo/GithubResponse.java
backend/src/main/java/heartbeat/exception/RestResponseEntityExceptionHandler.java
backend/src/main/java/heartbeat/service/source/github/GithubService.java
backend/src/test/java/heartbeat/controller/source/GithubControllerTest.java

Context/Background
In order to calculate the metrics, should set source control access correctly and get related data.
Acceptance Criteria
Happy path
get Github verify status and source data back
Integrate with frontend to finish the flow of this verify request
Sad path
Warning code when verify request failed
Tech information
What requests send from this verify request in existing master codebase
Refactor the request
Request to the real server for now as mock sever is not ready
Design API more Restful
Out of scope
Frontend
Testing
UT - yes

ADM-309 T5D - [backend] [Config] - Source control section

---

.github/workflows/BuildAndDeploy.yml

Reverts au-heartbeat/HeartBeat#185

Revert "Adm 384"

---

.github/workflows/BuildAndDeploy.yml

Reverts au-heartbeat/HeartBeat#187

Revert "Adm 384.2 [stub]"

---

.github/workflows/BuildAndDeploy.yml

...
_Description_
_Description_
_Null_

Adm 384.3[stub]

---

.github/workflows/BuildAndDeploy.yml

ADM-384 T0 - [backend] - mock sever for config
ADM-384 T0 - [backend] - mock sever for config

ADM-384 fix: [stub] remove docker container before rm image

---

backend/src/main/java/heartbeat/controller/board/vo/request/BoardRequestParam.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/controller/board/BoardRequestFixture.java

delete boardName in boardRequestRaram when calling jira boards
_Null_

ADM-383 delete boardName in boardRequestRaram.

---

.github/workflows/BuildAndDeploy.yml

...
_Description_
_Description_
_Null_

ADM-384 fix: [stub] pull latest image from AWS ECR

---

.github/workflows/BuildAndDeploy.yml

ADM-384 T0 - [backend] - mock sever for config
ADM-384 T0 - [backend] - mock sever for config

ADM-384 fix: [stub] replace docker registry/repository variable

---

frontend/__tests__/src/client/SourceControlClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/SourceControl.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/clients/SourceControlClient.ts
frontend/src/exceptions/UnauthorizedException.ts

ADM-348 T5C - [frontend] [Config] - Source control section

---

.github/workflows/BuildAndDeploy.yml

...
_Description_
_Description_
_Null_

ADM-359 fix bug to run e2e

---

frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/home.ts
frontend/cypress/pages/metrics.ts

...
_Description_
_Description_
_Null_

ADM-359 pref e2e testing with POM rule

---

frontend/__tests__/src/client/BoardClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/Board.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/clients/BoardClient.ts

modify 404 error prompt message

ADM-359.3: [frontEnd] [Config] - Jira verify error message

---

backend/README.md
backend/src/main/resources/application-e2e.yml
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics.ts
frontend/vite.config.ts

...
_Description_
_Description_
_Null_

ADM-380 T0A [Backend] Replace jira backend with mock sever

---

frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics.ts

ADM-361 [frontend] [Metrics] Crew Settings - add e2e test

---

stubs/backend/buildkite/buildkite-stubs.yaml

...
_Description_
_Description_
_Null_

ADM-349 [stub] delete time param in buildkite-stubs.yaml

---

frontend/__tests__/src/components/Metrics/MetricsStep/Crews.test.tsx
frontend/__tests__/src/context/metricsSlice.test.tsx
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics.ts
frontend/src/components/Metrics/MetricsStep/Crews/index.tsx
frontend/src/context/Metrics/metricsSlice.tsx

Fix e2e test
Store the content after the updated crews settings

ADM-361 [frontend] [Metrics] Crew Settings

---

frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics.ts
frontend/src/components/Metrics/MetricsStep/index.tsx

1.fix e2e test 
2.classification component display

ADM-364 T9 - [frontend] [Metrics] Classification Settings

---

frontend/__tests__/src/client/PipelineToolClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/PipelineTool.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/clients/PipelineToolClient.ts
frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx
frontend/src/components/Metrics/ConfigStep/SourceControl/index.tsx
frontend/src/constants.ts

update the validation about pipelineTool for token
...
_Description_
_Description_
_Null_

ADM-350 Pipeline tool section validation update

---

.github/workflows/BuildAndDeploy.yml

...
_Description_
_Description_
_Null_

ADM-380 [stub] chore: trigger stub deploy

---

frontend/src/components/Metrics/ConfigStep/Board/index.tsx
frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx

fix board and pipeline checkbox error
can not select jira or classic jira and buileKite or GOCD
can  select jira or classic jira and buileKite or GOCD

Fix bug：fix board and pipeline checkbox error

---

frontend/__tests__/src/components/Metrics/MetricsStep/CycleTime.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/src/context/metricsSlice.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics.ts
frontend/src/components/Common/FormSelect/index.tsx
frontend/src/components/Common/MetricsSettingTitle/style.tsx
frontend/src/components/Metrics/MetricsStep/Classification/index.tsx
frontend/src/components/Metrics/MetricsStep/Crews/index.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx
frontend/src/context/Metrics/metricsSlice.tsx

1. store boardColumns
2. fix bug

ADM-363 [frontend] [Metrics] Cycle time settings

---

backend/src/main/resources/application.yml
frontend/__tests__/src/fixtures.ts
frontend/src/clients/PipelineToolClient.ts

check with backend and confirm the URL and add buildKite url in application yml
...
_Description_
_Description_
_Null_

ADM-350 Pipeline tool section

---

frontend/__tests__/src/fixtures.ts
frontend/src/clients/PipelineToolClient.ts
frontend/src/components/Metrics/ConfigStep/Board/index.tsx
frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx
frontend/src/constants.ts

refactor ZERO and EMPTY_STRING and restful path

ADM-350-FIX 

---

stubs/backend/buildkite/jsons/buildkite.organizations.XXXX.pipelines.builds.json

...
_Description_
_Description_
_Null_

ADM-385 feat: [stub] modify email json file to rebuild.

---

stubs/backend/buildkite/buildkite-stubs.yaml
stubs/backend/github/github-stubs.yaml

- mock buildkite info json for mock server.
- fix error path for stubs.yaml.
...
_Description_
_Description_
_Null_

ADM-385 feat: [stub] fix error path for stubs.yaml.

---

.github/workflows/BuildAndDeploy.yml

modify the environment variable of mockserver url
modify the environment variable of mockserver url

ADM-380 fix: modify the environment variable of mockserver url

---

backend/src/test/java/heartbeat/exception/RestResponseEntityExceptionHandlerTest.java

Add Test for RestResponseEntityExceptionHandler

ADM-407 add test for RestResponseEntityExceptionHandler

---

.github/workflows/BuildAndDeploy.yml
backend/build.gradle
backend/src/test/java/heartbeat/config/CacheConfigTest.java
backend/src/test/java/heartbeat/config/ThreadPoolConfigTest.java
backend/src/test/java/heartbeat/exception/RestResponseEntityExceptionHandlerTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/initialConfigState.ts
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics/config.ts
frontend/src/components/Metrics/ConfigStep/MetricsTypeCheckbox/index.tsx
frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/MetricsStepper/style.tsx
frontend/src/context/config/board/boardSlice.tsx
frontend/src/context/config/configSlice.tsx
frontend/src/context/config/pipelineTool/pipelineToolSlice.tsx
frontend/src/context/config/sourceControl/sourceControlSlice.tsx
infra/cloudformation.yml
infra/updateAwsResource

When the component validation is successful, user can click the next button and enter the metrics page
Next on the page can be clicked at any time
When the component validation is successful, user can click the next button

ADM 378 [Frontend][Config] Enter the metrics page after successful verification

---

frontend/__tests__/src/client/BoardClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/Board.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/clients/BoardClient.ts

**changes**
rewrite get params for classic jira from '/board/Classic Jira' to '/board/Classic_Jira' to satify backend requirement

ADM-375 T5G - [Backend] [Config]- Board section - ClassicJira verify

---

.github/workflows/BuildAndDeploy.yml
backend/build.gradle
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/config/CacheConfigTest.java
backend/src/test/java/heartbeat/config/ThreadPoolConfigTest.java
backend/src/test/java/heartbeat/controller/board/BoardRequestFixture.java
backend/src/test/java/heartbeat/exception/RestResponseEntityExceptionHandlerTest.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
frontend/__tests__/src/client/BoardClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/Board.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/initialConfigState.ts
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics/config.ts
frontend/src/clients/BoardClient.ts
frontend/src/components/Metrics/ConfigStep/MetricsTypeCheckbox/index.tsx
frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/MetricsStepper/style.tsx
frontend/src/context/config/board/boardSlice.tsx
frontend/src/context/config/configSlice.tsx
frontend/src/context/config/pipelineTool/pipelineToolSlice.tsx
frontend/src/context/config/sourceControl/sourceControlSlice.tsx
infra/cloudformation.yml
infra/updateAwsResource

- Add jira board service test
...
_Backend Coverage_
_Null_

ADM-404 add JiraServiceTest

---

frontend/__tests__/src/client/BoardClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/Board.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/clients/BoardClient.ts

**changes**
revert url change since unresolved comments

Revert "ADM-375 T5G - [Backend] [Config]- Board section - ClassicJira verify"

---

stubs/backend/jira/jira-stubs.yaml

...
_Description_
_Description_
_Null_

ADM-380 fix: [stub] fix stub board configuration url

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-404.1 fix JiraServiceTest

---

.github/workflows/BuildAndDeploy.yml

ADM-385 Update e2e port for frontend

---

.github/workflows/BuildAndDeploy.yml

stop container before delete image

ADM-378.1 stop container before delete image

---

.github/workflows/BuildAndDeploy.yml

ADM-385 update script for sit deploy

ADM-385 update script for sit deploy

---

backend/README.md
backend/src/main/resources/application-local.yml

…tion with mock server info easily
...
_Description_
_Description_
_Null_

Add application-local config to start app with mock server Info easily 

---

stubs/frontend/exportPage/generateReporter-stubs.yaml
stubs/frontend/exportPage/jsons/exportData.json
stubs/stub-service.yaml
stubs/stubs.yaml

Mock for Frontend for Export page using stubby4j.
get the successfull response when given correct path

ADM-395 MockServer for Frontend for Export page

---

stubs/frontend/exportPage/generateReporter-stubs.yaml

ADM-395 [stub] deploy mockServer

---

.github/workflows/BuildAndDeploy.yml

Restart stub after ec2 restarted

ADM-unknown [infra] add restart=always for stubs

---

stubs/frontend/exportPage/generateReporter-stubs.yaml

change generator report path
/api/v1/generateReporter
/generateReporter

ADM-395 [stub] change generator report path

---

frontend/src/context/Metrics/metricsSlice.tsx

ADM-365 [frontend] [Metrics] Deployment frequency settings

---

stubs/frontend/exportPage/generateReporter-stubs.yaml

post request configuration Cross Domain

ADM 395[stub] post request configuration Cross Domain

---

.github/workflows/BuildAndDeploy.yml
infra/docker-compose.yml

Pref mock server flow
Start the server with docker cli
Start the server with docker-compose
_Null_

ADM-395 pref pipeline

---

stubs/backend/jira/jira-stubs.yaml

...
- fix jira board mock server config
_Description_
_Description_
_Null_

ADM-375.4 fix jira board mock server config

---

stubs/backend/jira/jira-stubs.yaml

Add startAt on mockServer for get all done cards

ADM-375 [stub] Add startAt for All done cards

---

backend/src/main/resources/application-e2e.yml
backend/src/main/resources/application.yml

- fix: application yml
...
_Description_
_Description_
_Null_

ADM-375 fix: application yml

---

frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/style.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/SingleSelection/style.tsx

fix SingleSelection,PipelineSelection style

ADM-387 [frontend]Page Adaptation for Responsive

---

stubs/backend/buildkite/buildkite-stubs.yaml

- update backend pipelines config in buildKite
...
_Description_
- need add four fields in url
_Description_
_Null_

ADM-425 [stub] update backend pipelines config in buildKite

---

docs/README.md
infra/cloudformation.yml
infra/docker-compose-old.yml

Update the port to 4325 for old app

ADM-FIX Update port to 4325 for old app

---

backend/src/main/java/heartbeat/controller/pipeline/vo/response/PipelineStepsResponse.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
stubs/backend/buildkite/buildkite-stubs.yaml

- fixed the priority of the stub file matcher.

ADM-403 [Metric]Implement get pipeline information

---

backend/src/main/java/heartbeat/controller/pipeline/vo/response/PipelineTransformer.java
backend/src/test/java/heartbeat/controller/pipeline/BuildKiteControllerTest.java
backend/src/test/java/heartbeat/controller/pipeline/pipelineInfoData.json
backend/src/test/java/heartbeat/controller/pipeline/vo/response/PipelineTransformerTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java

- In BuildKite backend fix a field from 'id' to 'slug'
...
_Description_
_Description_
_Null_

fix a field from 'id' to 'slug'

---

frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/fixtures/testFile.json

fix some name conflict in e2e test

ADM-356 Fix name of type in e2e

---

frontend/__tests__/src/components/Metrics/ConfigStep/MetricsTypeCheckbox.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/components/Metrics/ConfigStep/MetricsTypeCheckbox/index.tsx
frontend/src/constants.ts

...
_Description_
_Description_
_Null_

Issue#311 [Feature] Add All select option for Dequired Data, make it easy to use 

---

frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics/config.ts
frontend/cypress/pages/metrics/metrics.ts

 ADM-426 [report]-add e2e test

---

.github/workflows/BuildAndDeploy.yml

ADM-441 add Vulnerabilities Scanner

---

backend/src/main/java/heartbeat/client/GitHubFeignClient.java
backend/src/main/java/heartbeat/controller/source/GithubController.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/main/java/heartbeat/service/source/github/GithubService.java
backend/src/test/java/heartbeat/controller/source/GithubControllerTest.java
backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java

Some optimizations were made to the code before making the asynchronous request changes
- reduce conference variable
- use Token Util to mask 
- delete [GitHub] in log

ADM-433 [config] [backend] Optimize GitHub verify service by asynchronous mode

---

backend/README.md
backend/build.gradle
backend/src/main/resources/application.yml

...
_Description_
_Description_
_Null_

issue#346 [Bug] fix backend Swagger

---

.buildkite/ops/build
.buildkite/ops/check
.buildkite/ops/deploy
.github/workflows/BuildAndDeploy.yml

...
_Description_
_Description_
_Null_

Shell check

---

frontend/__tests__/src/components/Metrics/MetricsStep/CycleTime.test.tsx
frontend/__tests__/src/context/metricsSlice.test.ts
frontend/__tests__/src/fixtures.ts
frontend/src/clients/report/ReportClient.ts
frontend/src/clients/report/dto/request.ts
frontend/src/components/Metrics/ConfigStep/Board/index.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/FlagCard.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/context/Metrics/metricsSlice.tsx

add treatFlagCardAsBlock field to redux,and add jiraBoardSetting to post request report

ADM-467 Organize generate report request body

---

.github/workflows/BuildAndDeploy.yml
frontend/__tests__/src/components/Metrics/MetricsStep/CycleTime.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/__tests__/src/context/metricsSlice.test.ts
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/useMetricsStepValidationCheckContext.test.tsx
frontend/cypress.config.ts
frontend/cypress/fixtures/ConfigFileForImporting.json
frontend/cypress/plugins/updateConfigJson.ts
frontend/src/clients/report/dto/request.ts
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/context/Metrics/metricsSlice.tsx
frontend/src/hooks/reportMapper/deploymentFrequency.ts
frontend/src/hooks/useMetricsStepValidationCheckContext.tsx

Organize generate report request body

ADM-467 ADM-467 Organize generate report request body

---

frontend/src/context/config/configSlice.ts

restore changes in config file
_Description_
_Description_
_Null_

ADM-411 T11- [frontend][Metrics] Save data in config file for metrics page

---

frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/cypress/fixtures/ConfigFileForImporting.json
frontend/src/components/Metrics/ConfigStep/DateRangePicker/index.tsx
stubs/backend/jira/jira-stubs.yaml

fix endDate from 00:00:00 to 23:59:59
_Description_
_Description_
_Null_

Fix endDate

---

frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/cypress/fixtures/ConfigFileForImporting.json
frontend/src/components/Metrics/ConfigStep/DateRangePicker/index.tsx
stubs/backend/jira/jira-stubs.yaml

Reverts au-heartbeat/Heartbeat#374

Revert "Fix endDate"

---

docs/src/pages/en/dev-center/responsibilities-TL.md

...
_Description_
_Description_
_Null_

docs(tl): add more responsibilities for tl

---

.buildkite/hooks/pre-exit
.buildkite/ops/build
.buildkite/ops/deploy
.buildkite/pipeline.yml
infra/cloudformation.yml
infra/updateAwsResource

- update cloudformation to config AWSBuildKiteStepsRole and ssh private key.
- deploy-infra ✅
- deploy ✅

Adm 413 BuildKite integration-Backend

---

frontend/cypress/pages/metrics/metrics.ts

fix e2e test
...
_Description_
_Description_
_Null_

ADM-434 fix e2e test

---

.buildkite/ops/build
.buildkite/ops/deploy
.buildkite/pipeline.yml

integrated mock server build step and deploy step into buildKite.

ADM-465.1 feat: build and deploy mock server [stub]

---

.buildkite/ops/build
.buildkite/ops/deploy
.buildkite/pipeline.yml

- fix buildKite pipeline
- refactor pipeline.yml

ADM-465.1: fix buildKite pipeline and refactor pipeline.yml [stub]

---

docs/src/pages/en/dev-center/way-of-working.md

ADM-465.1: add way of code working diagram in docs [docs][stub]

---

docs/src/config.ts
docs/src/pages/en/dev-center/report-calculation-diagrams.md
docs/src/pages/en/report-calculation-method.md

- Add calculation method doc for MTTR
- Add calculation method doc for ChangeFailureRate
- Add calculation method flow diagram for MTTR
- Add calculation method flow diagram for ChangeFailureRate

ADM-437: [docs] [spike] Calculation rule for Change failure rate and Mean time to recovery

---

frontend/src/components/Metrics/MetricsStepper/index.tsx

ADM-450 [Metrics] Active 'Next' button in metric page

---

infra/cloudformation.yml

ADM-464.1 add BuildKiteAgentEC2Instance device volumeSize[infra] Lanxin Wang A minute ago

ADM-464.1 add BuildKiteAgentEC2Instance device volumeSize[infra]

---

backend/build.gradle
backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/client/dto/board/jira/AllDoneCardsResponseDTO.java
backend/src/main/java/heartbeat/client/dto/board/jira/Assignee.java
backend/src/main/java/heartbeat/client/dto/board/jira/JiraCard.java
backend/src/main/java/heartbeat/client/dto/board/jira/JiraCardField.java
backend/src/main/java/heartbeat/client/dto/board/jira/Status.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/controller/board/dto/response/CardCustomFieldKey.java
backend/src/main/java/heartbeat/controller/board/dto/response/CardParent.java
backend/src/main/java/heartbeat/controller/board/dto/response/CardParentField.java
backend/src/main/java/heartbeat/controller/board/dto/response/FixVersion.java
backend/src/main/java/heartbeat/controller/board/dto/response/IssueType.java
backend/src/main/java/heartbeat/controller/board/dto/response/JiraProject.java
backend/src/main/java/heartbeat/controller/board/dto/response/Priority.java
backend/src/main/java/heartbeat/controller/board/dto/response/Reporter.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
docs/src/pages/en/report-calculation-method.md
frontend/src/clients/report/ReportClient.ts
frontend/src/components/Metrics/ConfigStep/Board/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx

- change API Model and use new package method to fetch jira cards data
...
_Description_
_Description_
_Null_

ADM-469 The field about Story Point that cannot be currently resolved is being retrieved.

---

docs/src/pages/en/report-calculation-method.md

- Update report calculation doc of mean time to recovery

ADM-437: [docs] [stub] update report calculation doc of mean time to recovery

---

backend/src/main/java/heartbeat/client/dto/pipeline/buildkite/BuildKiteBuildInfo.java
backend/src/main/java/heartbeat/controller/report/dto/response/AvgChangeFailureRate.java
backend/src/main/java/heartbeat/controller/report/dto/response/ChangeFailureRate.java
backend/src/main/java/heartbeat/controller/report/dto/response/ChangeFailureRateOfPipeline.java
backend/src/main/java/heartbeat/controller/report/dto/response/ReportResponse.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/service/report/ChangeFailureRateCalculator.java
backend/src/main/java/heartbeat/service/report/DeploymentFrequencyCalculator.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/builder/BuildKiteJobBuilder.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/builder/DeployInfoBuilder.java
backend/src/test/java/heartbeat/service/report/CalculateChangeFailureRateTest.java
backend/src/test/java/heartbeat/service/report/CalculateDeploymentFrequencyTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/changeFailureRate.test.tsx
frontend/__tests__/src/hooks/reportMapper/leadTimeForChanges.test.tsx
frontend/src/clients/report/ReportClient.ts
frontend/src/clients/report/dto/response.ts
frontend/src/hooks/reportMapper/changeFailureRate.ts
frontend/src/hooks/reportMapper/leadTimeForChanges.ts

Change failure rate calculation
Postman:
frontend:

ADM-444[Report] [backend] Change failure rate calculation

---

backend/src/main/java/heartbeat/service/report/ChangeFailureRateCalculator.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/report/CalculateChangeFailureRateTest.java

fix change failure rate calculate duplicate issues

ADM-444 fix change failure rate calculate duplicate issues

---

.buildkite/pipeline.yml

- [format script shell.](https://github.com/au-heartbeat/Heartbeat/pull/387/commits/aa2892f3a88b1a923e98560a4aa2fd7a6190a1a2)

ADM-413 feat: format script shell.[infra][stub]

---

backend/src/main/java/heartbeat/client/dto/pipeline/buildkite/BuildKiteBuildInfo.java
backend/src/main/java/heartbeat/util/TimeUtil.java
backend/src/test/java/heartbeat/util/TimeUtilTest.java
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/changeFailureRate.test.tsx
frontend/src/hooks/reportMapper/changeFailureRate.ts

Bugs caused by accuracy issues in modifying data

ADM-444FIX  Bugs caused by accuracy issues in modifying data

---

.buildkite/pipeline.yml
ops/deploy.sh

ADM-464 feat: upload e2e vidoes artifact

---

.github/workflows/BuildAndDeploy.yml

- disable some GitHub actions.

ADM-413 feat: disable some GitHub actions.

---

frontend/__tests__/src/components/Metrics/MetricsStep/CycleTime.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/RealDone.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/context/metricsSlice.test.ts
frontend/src/components/Metrics/MetricsStep/CycleTime/FormSelectPart.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx
frontend/src/components/Metrics/MetricsStep/RealDone/index.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/context/Metrics/metricsSlice.tsx

save data in cycleTime settings when import a json file
The card is: https://trello.com/c/2BZENVx5

ADM-428: import cycleTime

---

.buildkite/pipeline.yml
ops/deploy.sh

inorder to fix AWS EC2 E2E instances

ADM-464 fix IP of AWS EC2 E2E instances and add login auth[infra]

---

backend/src/main/java/heartbeat/client/BuildKiteFeignClient.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/util/TimeUtil.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java

fixed bug , this bug is we can't get steps when select org and pipeline , now it can get all the steps in real buildkite.

ADM-470 fix bug that can't get steps in metrics page

---

backend/src/main/java/heartbeat/service/report/WorkDay.java

- fix WorkDay method logic
...
_Description_
_Description_
_Null_

ADM 434 Jira board calculate CycleTime

---

ops/infra/updateAwsResource.sh

- refacfor infra script to exiting gracefully.

ADM-464 feat: deploy [infra].

---

docs/src/pages/en/dev-center/report-calculation-diagrams.md
docs/src/pages/en/report-calculation-method.md

- [docs] add velocity and cycle time logic image
...
_Description_
_Description_
_Null_

ADM 434 Doc: [docs] add velocity and cycle time logic image

---

frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/classfication.test.tsx
frontend/src/clients/Httpclient.ts
frontend/src/clients/report/dto/response.ts
frontend/src/hooks/reportMapper/classification.ts

fix the type for Classification pairs value from string to number
update httpClient timeout to 300000ms
...
_Description_
_Description_
_Null_

ADM - 442 Fix the frontend type about Classification

---

backend/src/main/java/heartbeat/controller/report/dto/response/CycleTime.java
backend/src/main/java/heartbeat/controller/report/dto/response/Velocity.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/report/calculator/CycleTimeCalculator.java
backend/src/test/java/heartbeat/controller/report/GenerateReporterControllerTest.java
backend/src/test/java/heartbeat/service/report/CycleTimeCalculatorTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

...
_Description_
_Description_
_Null_

ADM-434 DTO rename

---

docs/src/config.ts
docs/src/pages/en/dev-center/export-csv.md
docs/src/pages/en/dev-center/flow-diagrams.md
docs/src/pages/en/dev-center/sequence-diagrams.md

Update flow diagram and export csv

ADM-448 [docs] [stub] [infra] Update flow diagram and export csv

---

frontend/src/components/Metrics/ConfigStep/Board/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx

Fix board token encryption issues

FixTokenBug fix board token encryption issues

---

backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java

- [optimize concurrent requests for Buildkite steps.](https://github.com/au-heartbeat/Heartbeat/commit/2c874e1a92ab7a7bb582d112c78b044accc093e2)

Adm 422 optimize buildkite get build steps.

---

docs/src/config.ts

Fix the issue that the export csv path is wrong

ADM-448 [docs] fix the issue that the export csv path is wrong

---

frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics/metrics.ts

ADM-455 Value in classification disappear after being back to metrics page from report page

---

backend/src/main/java/heartbeat/service/report/calculator/CycleTimeCalculator.java
frontend/cypress/pages/metrics/report.ts

- fix e2e test for report page
...
_Description_
_Description_
_Null_

ADM-434 - [report] - [backend] Jira board calculate Velocity and CycleTime

---

docs/src/pages/en/dev-center/sequence-diagrams.md

- [update buildkite diagrams.](https://github.com/au-heartbeat/Heartbeat/commit/1b6c7d372afa2420bfb8b120e4a7f49e7a5b9af2)

Adm 422 [doc]update buildkite diagrams.

---

frontend/__tests__/src/components/Metrics/MetricsStep/Classification.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/CycleTime.test.tsx
frontend/__tests__/src/context/configSlice.test.ts
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/useVerifySourceControlEffect.test.tsx
frontend/cypress/pages/metrics/metrics.ts
frontend/src/constants.ts
frontend/src/context/Metrics/metricsSlice.tsx
frontend/src/context/config/configSlice.ts

Change the warning display time to 4 seconds.
Change classification warning message.

ADM-452.1 Change the warning display time to 4 seconds

---

backend/src/main/java/heartbeat/service/report/LeadTimeForChangesCalculator.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/main/java/heartbeat/util/GithubUtil.java
backend/src/test/java/heartbeat/util/GithubUtilTest.java
docs/src/pages/en/report-calculation-method.md

* Fix git repo parser issue
* Fix nullpointerexception issue
* Use real github token key
...
_Description_
_Description_
_Null_

Adm 436 - Fix git repo parser issue

---

docs/src/pages/en/dev-center/flow-diagrams.md
docs/src/pages/en/report-calculation-method.md

*  update doc and data flow for LeadTimeForChanges
...
_Description_
_Description_
_Null_

Doc - Adm 436 update doc and data flow for LeadTimeForChanges

---

frontend/__tests__/src/context/metricsSlice.test.ts
frontend/src/components/Metrics/MetricsStep/Classification/index.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/style.tsx
frontend/src/context/Metrics/metricsSlice.tsx

Reverts au-heartbeat/Heartbeat#450

Revert "ADM-452.3 [frontend] Add Waring message case"

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/pages/metrics/metrics.ts
frontend/cypress/pages/metrics/report.ts

- refactor report e2e test use POM
...
_Description_
_Description_
_Null_

Refactor report e2e test use POM

---

docs/src/pages/en/dev-center/export-csv.md
docs/src/pages/en/dev-center/sequence-diagrams.md

ADM-446 [docs] Modify case issues

---

frontend/__tests__/src/components/Metrics/MetricsStep/RealDone.test.tsx
frontend/__tests__/src/context/metricsSlice.test.ts
frontend/src/components/Metrics/MetricsStep/RealDone/index.tsx
frontend/src/constants.ts
frontend/src/context/Metrics/metricsSlice.tsx

when imported json file has doneColumns, it will compare with options for Real done component (the options were defined by jira verified response and selected done columns in cycleTimeSettings)  to verify if imported doneColumns is effective. If imported one has value that doesn't exist in options, show warning message: 'Some selected doneStatus in import data might be removed'.
The card link is: https://trello.com/c/i1eix9d1

ADM-493 Verify import config file for RealDone[frontend][backend]

---

frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/DeploymentFrequencySettings.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/SingleSelection.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/LeadTimeForChanges.test.tsx
frontend/__tests__/src/hooks/useMetricsStepValidationCheckContext.test.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/style.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/index.tsx
frontend/src/components/Metrics/MetricsStep/LeadTimeForChanges/index.tsx
frontend/src/hooks/useMetricsStepValidationCheckContext.tsx

Reverts au-heartbeat/Heartbeat#458

Revert "ADM-462 [Metrics] duplicated pipeline error message improvement"

---

backend/build.gradle

update lib of org.apache.commons:commons-text

ADM-373 update lib to fix pipeline[frontend][backend][docs]

---

backend/build.gradle

Reverts au-heartbeat/Heartbeat#459

Revert "ADM-373 update lib to fix pipeline[frontend][backend][docs]"

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java

ADM 373.3: log generate csv error

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java

ADM-373.4: [frontend] [backend] log generate csv error

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java

Reverts au-heartbeat/Heartbeat#476

Revert "ADM-373.4: [frontend] [backend] log generate csv error"

---

backend/src/main/java/heartbeat/exception/FileIOException.java
backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java
backend/src/test/java/heartbeat/service/report/CSVFileGeneratorTest.java

debug error log
...
_Description_
_Description_
_Null_

Adm 373.4[frontend][backend]

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java

Use absolute path to generate csv

ADM-373.4: [frontend] [backend] use absolute path to generate csv

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java

ADM-373.4: [frontend] [backend] modify create csv method

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java

Reverts au-heartbeat/Heartbeat#480

Revert "ADM-373.4: [frontend] [backend] modify create csv method"

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java

Reverts au-heartbeat/Heartbeat#479

Revert "ADM-373.4: [frontend] [backend] use absolute path to generate csv"

---

backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java

Reverts au-heartbeat/Heartbeat#464

Revert "Adm 436 [backend]Leadtime for changes calculation"

---

frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/style.tsx

duplicated pipeline error message improvement

ADM-462 [Metrics] [frontend] duplicated pipeline error message improvement

---

backend/src/main/java/heartbeat/service/report/LeadTimeForChangesCalculator.java

- [fix calculate logic of Lead time for changes.](https://github.com/au-heartbeat/Heartbeat/pull/469/commits/6ccabeeffcd90f6fe91c642edd0211f1916521bf)
_Description_
_Description_
_Null_

ADM-436 feat:[backend] fix calculate logic of Lead time for changes.

---

frontend/__tests__/src/context/metricsSlice.test.ts
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/constants.ts

rewrite test description for selector function in metricsSlice; delete unused code(use code to handle show warning message when steps is empty)
_Description_
_Description_
_Null_

Adm 493 refactor test description and delete unused code[frontend][backend]

---

frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/style.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/index.tsx
frontend/src/components/Metrics/MetricsStep/LeadTimeForChanges/index.tsx

ADM-462 [frontend] duplicated pipeline error message improvement

---

frontend/src/components/Metrics/ConfigStep/MetricsTypeCheckbox/index.tsx

fix Data lost and status incorrect after being back to config page

ADM-483 [frontend] Data lost and status incorrect after being back to config page

---

backend/src/main/java/heartbeat/controller/report/dto/response/AvgLeadTimeForChanges.java
backend/src/main/java/heartbeat/service/report/LeadTimeForChangesCalculator.java
backend/src/test/java/heartbeat/service/report/CalculateLeadTimeForChangesTest.java
backend/src/test/java/heartbeat/service/report/ClassificationFixture.java

- [[backend] exclude lead times which have not pr merge time.](https://github.com/au-heartbeat/Heartbeat/pull/498/commits/2d5a6e2fd42bb239152045838fc110e074719b6f)
_Description_
_Description_
_Null_

Adm 436 [backend] Leadtime for changes calculation

---

frontend/src/components/Common/ReportForThreeColumns/index.tsx
frontend/src/constants.ts

Reverts au-heartbeat/Heartbeat#504

Revert "ADM-508 [Frontend]Remove average from export summary"

---

frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/pages/metrics/config.ts
frontend/cypress/pages/metrics/metrics.ts

In this pr, we enhance E2E to cover back scenario in createANewProject & importAProject.
_Description_
_Description_
_Null_

Adm 488 [frontend]Enhance E2E to cover back scenario

---

backend/build.gradle

upgrade version:
- commons-fileupload:commons-fileupload
- org.yaml:snakeyaml

Adm 511  [backend] [frontend] Upgrade spring-related dependencies

---

backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/report/BoardCsvFixture.java
stubs/backend/jira/jira-stubs.yaml

ADM-372.1 [backend] [stub] [frontend] fix e2e

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/report/BoardCsvFixture.java
backend/src/test/java/heartbeat/service/report/CSVFileGeneratorTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

ADM-372.3 [backend] fix board csv display error

---

backend/src/main/java/heartbeat/client/dto/board/jira/JiraCardWithFields.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/resources/fields.json

- Fix `sprint` not display issue
- Fix `Story point estimate` not display as an integer
- Consider the "Flag" as "Block" case

ADM-372: [backend] Fix CSV data display issue

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java

ADM-372 [backend] rename

---

frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/meanTimeToRecovery.test.tsx
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/fixtures/ConfigFileForImporting.json
frontend/cypress/pages/metrics/report.ts
frontend/src/clients/report/dto/response.ts
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/constants.ts
frontend/src/hooks/reportMapper/meanTimeToRecovery.ts
frontend/src/hooks/reportMapper/report.ts

Change in frontend to get the data and show it in report view page for MTTR section
_Description_
_Description_
_Null_

ADM 451: [frontend] MTTR

---

backend/src/main/java/heartbeat/service/report/GenerateReporterService.java

Fix report error issue when only select board metics.

ADM-445 [backend] fix report error issue

---

frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/meanTimeToRecovery.test.tsx
frontend/src/hooks/reportMapper/meanTimeToRecovery.ts

In this PR, we fix the issue about the time conversion logic.
_Description_
_Null_

ADM-451: Fix the time conversion issue

---

frontend/src/components/Metrics/ReportStep/index.tsx

...
_Description_
_Description_
_Null_

ADM-451: [frontend] MTTR

---

frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/cycleTime.test.tsx
frontend/__tests__/src/hooks/reportMapper/deploymentFrequency.test.tsx
frontend/src/hooks/reportMapper/cycleTime.ts
frontend/src/hooks/reportMapper/deploymentFrequency.ts
frontend/src/hooks/reportMapper/reportUIDataStructure.ts

ADM 514: [frontend] Number format for display purpose in Export page

---

frontend/cypress/e2e/createANewProject.cy.ts

Fix some e2e test issue in this pr.
_Description_
_Description_
_Null_

ADM-514: [frontend] fix e2e test issue

---

frontend/index.html
ops/infra/nginx.conf

...
_Description_
_Description_
_Null_

Adm 516 [frontend][backend][stub] fix redirect and app assets issue

---

frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/fixtures/fixtures.ts

ADM-471.1 [frontend] [backend] [stub] fix e2e issue

---

frontend/__tests__/src/client/BoardClient.test.ts
frontend/__tests__/src/client/CSVClient.test.ts
frontend/__tests__/src/client/MetricsClient.test.ts
frontend/__tests__/src/client/PipelineToolClient.test.ts
frontend/__tests__/src/client/ReportClient.test.ts
frontend/__tests__/src/client/SourceControlClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/Board.test.tsx
frontend/__tests__/src/components/Metrics/ConfigStep/PipelineTool.test.tsx
frontend/__tests__/src/components/Metrics/ConfigStep/SourceControl.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/clients/Httpclient.ts
frontend/src/exceptions/TimeoutException.ts

- Use hintInfo defined in backend to show error message.
- Handle Timeout exception.

ADM-471: [frontend] Error handling enhancement for frontend 

---

backend/src/main/java/heartbeat/decoder/BuildKiteFeignClientDecoder.java
backend/src/test/java/heartbeat/decoder/BuildKiteFeignClientDecoderTest.java
docs/src/config.ts
docs/src/pages/en/dev-center/error-handle.md

- Add error handle doc to GitHub.

ADM-471: [backend] Add error handle doc to GitHub

---

backend/src/main/java/heartbeat/controller/board/dto/request/BoardType.java
backend/src/main/java/heartbeat/exception/FileIOException.java
backend/src/main/java/heartbeat/exception/InternalServerErrorException.java
backend/src/main/java/heartbeat/exception/RequestFailedException.java
backend/src/main/java/heartbeat/exception/RestResponseEntityExceptionHandler.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/test/java/heartbeat/controller/board/dto/request/BoardTypeTest.java
backend/src/test/java/heartbeat/exception/RestResponseEntityExceptionHandlerTest.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java

- Add log for FeignClient error.
- Format 5xx error response.

ADM-471: [backend] Error handle enhancement

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
docs/src/pages/en/dev-center/error-handle.md

- Update error handle doc
- Update error log.

ADM-471 [docs] [backend] update error handle doc

---

backend/src/main/java/heartbeat/exception/RestResponseEntityExceptionHandler.java
backend/src/test/java/heartbeat/exception/RestResponseEntityExceptionHandlerTest.java

ADM-471 [backend] handle default error

---

.github/workflows/Release.yaml

...
Images just push to ECR
Images push to [GitHub Registry](https://github.com/orgs/au-heartbeat/packages?repo_name=Heartbeat) when releasing
_Null_

Push image

---

docs/src/pages/en/dev-center/emoji-flow.md

[docs] ADM-503: add emoji flow diagram.

---

docs/src/config.ts
docs/src/pages/en/dev-center/solution-of-buildkite-issue.md

- Add doc about solution of BuildKite issue.

ADM-541 [docs] add doc about solution of BuildKite issue.

---

ops/infra/cloudformation.yml

- modify port value and redeploy ec2.

[frontend] [backend] [infra] modify port value and redeploy ec2.

---

docs/src/config.ts
docs/src/pages/en/dev-center/solution-of-buildkite-issue.md

- Add doc about solution of BuildKite issue.

ADM-541-NEW [docs] add doc about solution of BuildKite issue.

---

backend/src/main/java/heartbeat/controller/pipeline/PipelineController.java
backend/src/main/java/heartbeat/controller/report/GenerateReportController.java
backend/src/main/java/heartbeat/controller/source/GithubController.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java

- Delete log of Jira response, keep key info.
- Delete log of BuildKite response, keep key info.
- Delete log of GitHub response, keep key info.
- Delete log of token.

ADM-543: [backend] Delete the log of response

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

Reverts au-heartbeat/Heartbeat#572

Revert "ADM-540: [backend]Cycle time for undone cards"

---

frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx

Miss the comment of zhongren.
Need revert and add UT for it.

Revert "ADM-550 [Fox][frontend] - Real down reset issue"

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
stubs/backend/jira/jira-stubs.yaml
stubs/backend/jira/jsons/jira.issue.ADM-309.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-348.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-349.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-350.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-359.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-360.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-361.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-362.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-363.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-364.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-365.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-366.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-375.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-380.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-383.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-384.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-385.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-386.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-388.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-391.activityfeed.json

When export board CSV, only calculate cycle time for dong cards.

ADM-540: [backend]Cycle time for undone cards

---

frontend/__tests__/src/components/Metrics/ConfigStep/DateRangePicker.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/src/components/Metrics/ConfigStep/DateRangePicker/index.tsx

Reverts au-heartbeat/Heartbeat#578

Revert "ADM 551: [frontend] Adjust AUTO To date when user select From date"

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
stubs/backend/jira/jira-stubs.yaml
stubs/backend/jira/jsons/jira.issue.ADM-309.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-348.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-349.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-350.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-359.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-360.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-361.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-362.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-363.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-364.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-365.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-366.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-375.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-380.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-383.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-384.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-385.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-386.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-388.activityfeed.json
stubs/backend/jira/jsons/jira.issue.ADM-391.activityfeed.json

Reverts au-heartbeat/Heartbeat#588

Revert "Revert "ADM-540: [backend]Cycle time for undone cards""

---

frontend/__tests__/src/components/Metrics/ConfigStep/DateRangePicker.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/src/components/Metrics/ConfigStep/DateRangePicker/index.tsx

Reverts au-heartbeat/Heartbeat#587

Revert "Revert "ADM 551: [frontend] Adjust AUTO To date when user select From date""

---

frontend/__tests__/src/components/Metrics/ConfigStep/DateRangePicker.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/fixtures/NewConfigFileForImporting.json
frontend/cypress/fixtures/OldConfigFileForImporting.json
frontend/src/components/Metrics/ConfigStep/DateRangePicker/index.tsx
stubs/backend/jira/jira-stubs.yaml

Justify the time interval automatically generated on the config page and its related tests.

ADM-551:[frontend] Adjust AUTO To date when user select From date

---

frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx

When there are no done column in cycle time, Real done component will disappear.
_Description_
_Null_

ADM-550 [frontend] - Hide real done when no done column in cycle time

---

frontend/__tests__/src/components/Metrics/ConfigStep/ConfigStep.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/src/components/Metrics/ConfigStep/index.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx

Revert "ADM-546: [frontend] Performance optimization"

Revert "ADM-546: [frontend] Performance optimization"

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/service/board/jira/JiraColumnResult.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/report/calculator/CycleTimeCalculator.java
backend/src/main/java/heartbeat/service/report/calculator/model/FetchedData.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
docs/src/pages/en/dev-center/support-multiple-columns.md

Export data should be same with above and make sure it doesn’t include the duplicate card
_Description_
_Description_
_Null_

ADM-531: [backend] Support multiple Done columns

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/service/board/jira/JiraColumnResult.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/report/calculator/CycleTimeCalculator.java
backend/src/main/java/heartbeat/service/report/calculator/model/FetchedData.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
docs/src/pages/en/dev-center/support-multiple-columns.md
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/fixtures/NewConfigFileForImporting.json
frontend/cypress/fixtures/OldConfigFileForImporting.json
frontend/cypress/pages/metrics/config.ts
stubs/backend/jira/jira-stubs.yaml

Export data should be same with above and make sure it doesn’t include the duplicate card
_Description_
_Description_
_Null_

ADM-531: [backend] Support multiple Done columns 

---

frontend/__tests__/src/client/CSVClient.test.ts
frontend/__tests__/src/components/Metrics/ConfigStep/ConfigStep.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/Metrics/ConfigStep/index.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/tsconfig.json
frontend/vite.config.ts

The style-b2xxx is taking around 30 seconds to load, causing delays in creating a new profile. It's too slow, and we need to address this performance problem.

ADM-546-new: [frontend] Performance optimization

---

.gitignore
frontend/.eslintrc.json
frontend/.gitignore
frontend/.prettierignore
frontend/index.html

ADM-546:[frontend] modify config of pwa

---

frontend/src/components/Metrics/MetricsStepper/index.tsx

Reverts au-heartbeat/Heartbeat#616

Revert "ADM-566:[frontend] fix the next button can not be disabled bug"

---

frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/src/components/Metrics/MetricsStepper/index.tsx

...
_Description_
_Description_
_Null_

ADM-566:[frontend] fix the next button can not be disabled bug 

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/leadTimeForChanges.test.tsx

modify lead time property name
_Description_
_Description_
_Null_

ADM-507:[frontend][backend] modify lead time property name

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/hooks/reportMapper/leadTimeForChanges.test.tsx

Reverts au-heartbeat/Heartbeat#620

Revert "ADM-507:[frontend][backend] modify lead time property name"

---

backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-569: [backend]Change the calculation method of Multiple Done columns

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

Reverts au-heartbeat/Heartbeat#626

Revert "ADM-569: [Backend]Change the calculation method of Multiple Done columns"

---

stubs/backend/jira/jira-stubs.yaml

...
_Description_
_Description_
_Null_

ADM-574:[stub] fix jql in jira stub yaml

---

backend/src/main/java/heartbeat/client/dto/pipeline/buildkite/BuildKiteBuildInfo.java
backend/src/main/java/heartbeat/client/dto/pipeline/buildkite/DeployInfo.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/client/dto/pipeline/buildkite/BuildKiteBuildInfoTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/builder/BuildKiteJobBuilder.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/builder/DeployInfoBuilder.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

ADM-523 feat: change calculateion of pipeline failure rate

ADM-523 feat: change calculateion of pipeline failure rate

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/util/BoardUtil.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/util/BoardUtilTest.java
backend/src/test/java/heartbeat/util/StatusChangedItemsListAndCycleTimeInfosListFixture.java

...
_Description_
_Description_
_Null_

ADM-555:[backend] fix origin flag time when treatFlagCardAsBlock is true

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java

...
_Description_
_Description_
_Null_

 ADM-577:[backend]fix: check isRealDoneCard by getting the last time from undone to realDone 

---

docs/src/pages/en/dev-center/cycle-time-calculation.md

...
_Description_
_Description_
_Null_

ADM-577:[docs]update flow chart about done card

---

README.md
README.zh-CN.md
docs/src/pages/en/dev-center/solution-of-buildkite-issue.md
docs/src/pages/en/dev-center/start-e2e-test-in-local.md
docs/src/pages/en/dev-center/way-of-working.md

Add some infos about e2e test and consummate progress of our project.

[docs] add progress

---

ops/infra/Dockerfile.backend

...
_Description_
_Description_
_Null_

ADM-552:[backend]fix: update the base environment for backend

---

frontend/__tests__/src/utils/Util.test.tsx
frontend/src/context/Metrics/metricsSlice.tsx
frontend/src/context/config/configSlice.ts
frontend/src/utils/util.ts

ADM-552:[frontend]fix: fix frontend test
_Description_
_Description_
_Null_

ADM-552:[frontend]fix: fix frontend test

---

release-notes/20231009.md

...
_Description_
_Description_
_Null_

ADM-581:[docs]Add release notes for v1.1.0

---

frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/__tests__/src/context/metricsSlice.test.ts
frontend/__tests__/src/utils/Util.test.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/context/Metrics/metricsSlice.tsx
frontend/src/context/config/configSlice.ts
frontend/src/utils/util.ts

...
_Description_
_Description_
_Null_

ADM-552:[frontend]feat: sort pipelines and delete the PipelineMetricSelection when there is no step

---

release-notes/20231009.md

...
_Description_
_Description_
_Null_

ADM-581:[docs]Modify release notes for v1.1.0

---

frontend/src/clients/MetricsClient.ts
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx

ADM-552:[frontend]fix: fix the situation of NoContent
_Description_
_Description_
_Null_

ADM-552:[frontend]fix: fix the situation of NoContent

---

docs/src/pages/en/dev-center/tech-spikes.md

...
_Description_
_Description_
_Null_

ADM-475:[docs]update spike document to filter generated csv data

---

backend/src/main/java/heartbeat/client/dto/board/jira/HistoryDetail.java
backend/src/main/java/heartbeat/controller/report/dto/request/JiraBoardSetting.java
backend/src/main/java/heartbeat/enums/AssigneeFilterMethod.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
docs/src/pages/en/dev-center/way-of-working.md
frontend/__tests__/src/components/Metrics/MetricsStep/Crews.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/context/metricsSlice.test.ts
frontend/__tests__/src/fixtures.ts
frontend/src/clients/report/dto/request.ts
frontend/src/components/Metrics/MetricsStep/Crews/AssigneeFilter.tsx
frontend/src/components/Metrics/MetricsStep/Crews/index.tsx
frontend/src/components/Metrics/MetricsStep/Crews/style.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/constants.ts
frontend/src/context/Metrics/metricsSlice.tsx
frontend/src/fileConfig/fileConfig.ts

ADM-587:[frontend][backend]feat: Support two ways of filtering Jira cards with assignee
_Description_
_Description_
_Null_

ADM-587:[frontend][backend]feat: Support two ways of filtering Jira cards with assignee

---

frontend/__tests__/src/components/Metrics/MetricsStep/Crews.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/pages/metrics/config.ts
frontend/cypress/pages/metrics/metrics.ts
frontend/cypress/pages/metrics/report.ts
frontend/src/components/Common/MetricsSettingButton/index.tsx
frontend/src/components/Common/MetricsSettingButton/style.tsx
frontend/src/components/Common/MetricsSettingTitle/index.tsx
frontend/src/components/Common/MetricsSettingTitle/style.tsx
frontend/src/components/Common/ReportForThreeColumns/index.tsx
frontend/src/components/Common/ReportForTwoColumns/index.tsx
frontend/src/components/Common/ReportForTwoColumns/style.tsx
frontend/src/components/Metrics/MetricsStep/Crews/AssigneeFilter.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/FormSelectPart.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/style.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/style.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx
frontend/src/components/Metrics/MetricsStep/style.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/MetricsStepper/style.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/components/Metrics/ReportStep/style.tsx

ADM-596:[frontend]feat: Optimize the hierarchy of metrics page
_Description_
_Description_
_Null_

ADM-596:[frontend]feat: Optimize the hierarchy of metrics page

---

frontend/__tests__/src/fixtures.ts
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/src/App.css
frontend/src/components/Common/MetricsSettingTitle/index.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx
frontend/src/components/Metrics/MetricsStep/CycleTime/style.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/style.tsx
frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/index.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx
frontend/src/components/Metrics/MetricsStep/style.tsx
frontend/src/components/Metrics/MetricsStepper/style.tsx
frontend/src/layouts/Header.tsx

ADM-596:[frontend]fix: fix the styles and tests of metrics-page
_Description_
_Description_
_Null_

ADM-596:[frontend]fix: fix the styles and tests of metrics-page

---

frontend/cypress/e2e/createANewProject.cy.ts

ADM-596:[frontend]fix: fix the e2e test
_Description_
_Description_
_Null_

ADM-596:[frontend]fix: fix the e2e test

---

frontend/src/clients/report/CSVClient.ts

...
_Description_
_Description_
_Null_

ADM-589:[frontend]feat: adjust the time stamp in exported csv file name

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-583:[backend] remove unused custom fields

---

backend/src/main/java/heartbeat/controller/board/dto/response/BoardConfigDTO.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/controller/board/BoardConfigResponseFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-583:[backend] export ignore target field when verify jira board

---

frontend/__tests__/src/context/metricsSlice.test.ts
frontend/src/context/Metrics/metricsSlice.tsx

…id warning message
...
_Description_
_Description_
_Null_

ADM-583:[frontend]feat: filter the saved target fields to avoid misleading warning

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java

...
_Description_
_Description_
_Null_

ADM-583:[backend] replace target fields' key with name

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-583:[backend] refactor: remove repeated code

---

frontend/src/components/Metrics/ReportStep/index.tsx

fix: fix the issue of inadequate test coverage
_Description_
_Description_
_Null_

ADM-584:[frontend]fix: fix the issue of inadequate test coverage

---

frontend/cypress/e2e/createANewProject.cy.ts

Fix the E2E test where CheckMetricCSV is not defined.
...
_Null_

ADM-588:[frontend]fix: define the check metric

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/client/dto/board/jira/JiraCardField.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/controller/board/dto/response/CardCollection.java
backend/src/main/java/heartbeat/controller/report/dto/response/Velocity.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/report/CSVFileGeneratorTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

Fix the issue when calculate and export a card's story point from 0.5 to 0 **in velocity and cycle time metric**
...
_Description_
_Description_
_Null_

Adm 627: The story point When calculate and export from 0.5 to 0

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

ADM-636: update issue template to let user give more inoformation.

---

frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/context/Metrics/metricsSlice.tsx

Change the request body of jiraColumns with the Jira real column value
_Null_

[frontend]Column mapping from name to statues

---

frontend/__tests__/src/components/Common/NotificationButton/NotificationButton.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/__tests__/src/hooks/useNotificationLayoutEffect.test.tsx
frontend/cypress/pages/metrics/metrics.ts
frontend/cypress/pages/metrics/report.ts
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/constants.ts

...
_Description_
_Description_
_Null_

ADM-623:[frontend] feat: fix the issue of review.

---

docs/src/content/docs/en/designs/refinement-on-generate-report.mdx

...
_Description_
_Description_
_Null_

ADM-609:[docs]feat: add API Design in refinement-on-generate-report

---

frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/__tests__/src/hooks/useGenerateReportEffect.test.tsx
frontend/src/constants.ts

...
_Description_
_Description_
_Null_

ADM-640:[frontend] feat: fix the issue of code review.

---

.buildkite/pipeline.yml

Update the pipeline.yml file to make the commit message case-insentive.
The **(?i)** part at the beginning of the regex pattern enables case-insensitive matching. 
**So, regardless of whether the commit message contains "[backend]", "[Backend]", or any other case variation, it will be considered a match and trigger related events.**
_Null_

ADM-645:[infra]feat: ignore the case of the commit message

---

.buildkite/pipeline.yml

Reverts au-heartbeat/Heartbeat#769

Revert "ADM-645:[infra]feat: ignore the case of the commit message"

---

docs/src/content/docs/en/issue-solutions/solution-of-buildkite-issue.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

[Docs]：add issues in solution-of-buildKite-issue

---

backend/src/main/java/heartbeat/controller/crypto/CryptoController.java
backend/src/main/java/heartbeat/controller/crypto/request/EncryptRequest.java
backend/src/main/java/heartbeat/controller/crypto/response/EncryptResponse.java
backend/src/main/java/heartbeat/exception/EncryptProcessException.java
backend/src/main/java/heartbeat/exception/RestResponseEntityExceptionHandler.java
backend/src/main/java/heartbeat/service/crypto/EncryptDecryptService.java
backend/src/main/java/heartbeat/util/EncryptDecryptUtil.java
backend/src/test/java/heartbeat/controller/crypto/CryptoControllerTest.java
backend/src/test/java/heartbeat/service/crypto/EncryptDecryptServiceTest.java
backend/src/test/java/heartbeat/util/EncryptDecryptUtilTest.java

...
_Description_
_Description_
_Null_

Adm 619[Backend]Encrypt exported content when save configuration

---

frontend/cypress.config.ts

… upgraded.
...
_Description_
_Description_
_Null_

ADM-647: [frontend] test: add field to output the voide after cypress upgraded.

---

backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java

...
_Description_
_Description_
_Null_

ADM-658:[backend]fix: format test fixture

---

frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/fixtures/metric.csv
frontend/cypress/pages/metrics/config.ts
frontend/cypress/pages/metrics/metrics.ts
frontend/cypress/pages/metrics/report.ts

...
_Description_
_Description_
_Null_

ADM-651:[frontend] Do some refactorings for e2e

---

docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

[docs] fix: fix key and slug

---

.github/ISSUE_TEMPLATE/bug_report.yml

...
_Description_
_Description_
_Null_

[ADM-655][frontend]fix: fix description

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/WorkDay.java
docs/src/i18n/en/nav.ts

...
_Description_
When export in board data, the accuracy of the data has 0.01 difference.
Accuracy calibration.
_Null_

ADM-659:[backend] Calibration board data accuracy

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/WorkDay.java

Reverts au-heartbeat/Heartbeat#801

Revert "ADM-659:[backend] Calibration board data accuracy"

---

backend/src/main/java/heartbeat/config/SwaggerConfig.java

...
_Description_
_Description_
_Null_

ADM-620:[backend]feat: add swagger config to get LocalHost

---

backend/src/main/java/heartbeat/config/SwaggerConfig.java

...
_Description_
_Description_
_Null_

ADM-619:[backend]fix: hard code new server url in SwaggerConfig

---

ops/infra/docker-compose.yml

...
_Description_
_Description_
_Null_

ADM-620:[frontend][backend]chore: add fake env in backend env

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/WorkDay.java

Reverts au-heartbeat/Heartbeat#804

Revert "Revert "ADM-659:[backend] Calibration board data accuracy""

---

backend/src/main/java/heartbeat/controller/crypto/request/EncryptRequest.java
backend/src/test/java/heartbeat/controller/crypto/CryptoControllerTest.java

...
_Description_
_Description_
_Null_

ADM-619:[backend]feat: add regexp for password

---

frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/pages/metrics/metrics.ts

...
_Description_
_Description_
_Null_

ADM-513:[frontend] Add e2e test.

---

docs/src/content/docs/en/designs/cycle-time-calculation.mdx

_Description_
_Description_
_Null_

ADM-659:[docs]feat: add remark for round up four and add five calculation

---

docs/src/content/docs/en/spikes/tech-spikes-encrypt-decrypt-configuration.mdx

...
_Description_
_Description_
_Null_

ADM-620:[docs]feat: change exception handling in table

---

backend/src/main/java/heartbeat/controller/crypto/request/DecryptRequest.java

...
_Description_
_Description_
_Null_

ADM-620:[backend]refactor: add . for encryptedData NotBlank message

---

.github/workflows/BuildAndDeploy.yml

Remove installation of python for buildkite check
_Description_
_Description_
_Null_

refactor(ci): remove python install

---

frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/pages/metrics/metrics.ts

...
_Description_
_Description_
_Null_

ADM-651:[frontend] Do some refactorings for e2e.

---

README.md
docs/src/content/docs/en/spikes/tech-spikes-impact-of-status-and-column-name-change.mdx

...
_Description_
_Description_
_Null_

ADM-628:[docs] update known issues about readme and add tech spike result of impact regarding status and column name change

---

docs/src/content/docs/en/spikes/tech-spikes-encrypt-decrypt-configuration.mdx
docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-github.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

Adm 679[docs]Spike How to spilt current verify for github

---

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-github.mdx

...
_Description_
_Description_
_Null_

ADM-679:[docs]fix: change path and response

---

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

Adm-678[docs]: fix path and response

---

frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/cypress/e2e/importAProject.cy.ts
frontend/cypress/fixtures/config.json
frontend/cypress/pages/metrics/report.ts
frontend/src/components/HomeGuide/index.tsx
frontend/src/components/HomeGuide/style.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/components/Metrics/MetricsStepper/style.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/components/Metrics/ReportStep/style.tsx
frontend/src/constants/commons.ts
frontend/src/layouts/style.tsx

...
_Description_
_Description_
_Null_

ADM-664: [frontend] feat: add save button in report step

---

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-678[docs] fix:fix text name

---

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-678[docs]: add docs for spike buildKite

---

frontend/scripts/runE2eWithServer.ts

...
_Description_
The port check is abnormal on the M1 chip.
_Description_
Fixed the port detect issue on M1 chip.

ADM-573: [frontend] fix E2E port detect bug on M1 chip

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-700:[backend]feat: handle exception for get column status

---

frontend/.eslintrc.json
frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx
frontend/src/components/Metrics/MetricsStep/RealDone/index.tsx
frontend/tsconfig.json

...
Import from config.json with status map to done, change the status map in the cycle time settings, real done is not cleared
_Description_
The real done settings should be cleared.

ADM-666: [frontend] fix cycletime setting from done to another status, the real done not cleared

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

Adm 700[backend]: fix status bug and add log

---

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-board.mdx

ADM-612:[docs]feat: fix Sequence Diagram

---

backend/.gitignore
backend/src/main/resources/log4j2.xml
ops/infra/Dockerfile.backend

Not store log into file and rolling up
_Description_
_Null_

feat(log): add backend log rolling file strategy

---

docs/src/content/docs/en/spikes/tech-spikes-encrypt-decrypt-configuration.mdx
docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-678[docs]:fix path and error handler

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-github.mdx
docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-github.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

Adm 679[docs]feat: change file title

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-github.mdx

...
_Description_
_Description_
_Null_

ADM-679:[docs]fix: fix exception message

---

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx

...
_Description_
_Description_
_Null_

ADM-678:[docs]feat: add 500 error

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-github.mdx

...
_Description_
_Description_
_Null_

ADM-679:[docs]fix: change c3 to Sequence Diagram

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-612:[docs]feat: refactor docs

---

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx

...
_Description_
_Description_
_Null_

ADM-612:[docs]feat: fix docs

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java

This reverts commit 0dfcb150b4f25b4b96fa3b3653e7e0aa209dd062.
...
_Description_
_Description_
_Null_

Revert "ADM-700:[backend]chore: add log for jira verify"

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-612:[docs]feat: update board verify token element

---

frontend/__tests__/src/components/ErrorContent/index.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/__tests__/src/layouts/Header.test.tsx
frontend/__tests__/src/router.test.tsx
frontend/cypress/e2e/createANewProject.cy.ts
frontend/src/components/ErrorContent/index.tsx
frontend/src/components/Metrics/MetricsStepper/index.tsx
frontend/src/config/routes.ts
frontend/src/constants/router.ts
frontend/src/layouts/Header.tsx

the home icon should't appear in home page, appear in other page
_Description_
_Description_
_Null_

ADM-698:[frontend]:home icon should't appear in home page

---

frontend/__tests__/src/components/Common/DateRangeViewer/DateRangeViewer.test.tsx
frontend/src/components/Common/DateRangeViewer/index.tsx
frontend/src/components/Common/DateRangeViewer/style.tsx
frontend/src/components/Metrics/MetricsStep/index.tsx
frontend/src/components/Metrics/MetricsStep/style.tsx
frontend/src/constants/template.ts

...
_Description_
_Description_
_Null_

Feat/adm 633 Frontend - replace date range styles 

---

frontend/__tests__/src/components/Common/DateRangeViewer/DateRangeViewer.test.tsx
frontend/src/components/Common/DateRangeViewer/style.tsx
frontend/src/constants/template.ts

...
_Description_
_Description_
_Null_

Feat/adm 633 [Frontend] fix ui details

---

frontend/.prettierignore
frontend/scripts/runE2eWithServer.ts

Fix localhost issue & add prettier ignore

ADM-573:[frontend]:  fix localhost issue & add prettier ignore

---

frontend/__tests__/src/context/configSlice.test.ts
frontend/__tests__/src/initialConfigState.ts
frontend/src/components/HomeGuide/index.tsx
frontend/src/context/config/configSlice.ts
frontend/src/layouts/Header.tsx

...
_Description_
_Description_
_Null_

ADM-650:[frontend]:  reset filled config data when go back to homepage

---

docs/src/content/docs/en/spikes/tech-timezone-problem.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-579:[docs]feat: add timezone problem spike docs

---

docs/src/content/docs/en/spikes/tech-spikes-support-multiple-instances-for-backend-service.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

Adm 672[docs] Support multiple instances for backend service

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-612:[docs]feat: add exception handler

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-612:[docs]feat: update exception handler

---

docs/src/content/docs/en/spikes/tech-timezone-problem.mdx

...
_Description_
_Description_
_Null_

ADM-579:[docs]feat: update spike trace content

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-612:[docs]feat: update board verify request

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/client/dto/board/jira/JiraBoardVerifyDTO.java
backend/src/main/java/heartbeat/client/dto/board/jira/Location.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/controller/board/JiraController.java
backend/src/main/java/heartbeat/controller/board/dto/request/BoardVerifyRequestParam.java
backend/src/main/java/heartbeat/controller/board/dto/response/JiraVerifyDTO.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/controller/board/BoardRequestFixture.java
backend/src/test/java/heartbeat/controller/board/JiraControllerTest.java
backend/src/test/java/heartbeat/controller/board/dto/request/BoardVerifyRequestFixture.java
backend/src/test/java/heartbeat/service/jira/JiraBoardVerifyDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-708:[backend]feat: add api  and service for board verify 

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/client/dto/board/jira/JiraBoardProject.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/controller/board/JiraController.java
backend/src/main/java/heartbeat/controller/board/dto/response/JiraVerifyResponse.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/controller/board/JiraControllerTest.java
backend/src/test/java/heartbeat/service/jira/JiraBoardVerifyDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-708:[backend]feat: add get board info api

---

frontend/src/clients/newHttpClient.ts

Add a new client to pass through the error to down stream so that business-api-clients could leverage more info from the error.
Also, other tickets is depend on this.
_Description_
_Description_
_Null_

ADM-714: [frontend]: feat: add a new client to pass through the error

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

Just for trigger the pipeline
...
_Description_
_Description_
_Null_

ADM-708:[docs]feat: update get info board

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/client/dto/board/jira/CardHistoryResponseDTO.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-729[backend]feat: can get all history for card

---

stubs/backend/jira/jsons/jira.issue.PLL-1320.activityfeed.json
stubs/backend/jira/jsons/jira.issue.PLL-1341.activityfeed.json

...
_Description_
_Description_
_Null_

ADM-729[stub]fix: change stub data to fix e2e

---

backend/src/main/java/heartbeat/enums/AssigneeFilterMethod.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-730:[backend]fix: fix the logic to get last assignee and get historical assignees

---

backend/src/main/java/heartbeat/client/GitHubFeignClient.java
backend/src/main/java/heartbeat/controller/source/GithubController.java
backend/src/main/java/heartbeat/controller/source/SourceTypeEnum.java
backend/src/main/java/heartbeat/controller/source/dto/GitHubResponse.java
backend/src/main/java/heartbeat/controller/source/dto/SourceControlDTO.java
backend/src/main/java/heartbeat/controller/source/dto/VerifyBranchRequest.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/test/java/heartbeat/TestFixtures.java
backend/src/test/java/heartbeat/controller/source/GithubControllerTest.java
backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java

...
_Description_
_Description_
_Null_

ADM-717[backend] Verify github and obtain github data with new API

---

frontend/__tests__/src/components/Common/NotificationButton/NotificationButton.test.tsx
frontend/__tests__/src/components/ErrorContent/index.test.tsx
frontend/__tests__/src/components/HomeGuide/HomeGuide.test.tsx
frontend/__tests__/src/components/Metrics/ConfigStep/MetricsTypeCheckbox.test.tsx
frontend/__tests__/src/components/Metrics/ConfigStep/PipelineTool.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/DeploymentFrequencySettings.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/src/components/Metrics/MetricsStep/MultiAutoComplete.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ExpiredDialog.test.tsx
frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/__tests__/src/hooks/useGenerateReportEffect.test.tsx
frontend/__tests__/src/hooks/useNotificationLayoutEffect.test.tsx
frontend/jest.config.json

Increase timeout value for unit testing to improve the stability. 
Some unit test cases are failed as timeout. 
No unit test cases are failed as timeout.

[ADM-634][frontend] Increase the timeout value and fix some warning messages

---

backend/src/main/java/heartbeat/controller/source/GithubController.java
backend/src/main/java/heartbeat/controller/source/SourceType.java

...
_Description_
_Description_
_Null_

ADM-717[backend]refactor: delete useless enum and useless default

---

frontend/__tests__/src/fixtures.ts
frontend/src/components/Metrics/MetricsStep/style.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/components/Metrics/ReportStep/style.tsx
frontend/src/constants/resources.ts

enhance style for calendar
_Description_
_Description_
_Null_

[frontend] ADM-652: enhance style for calendar

---

frontend/cypress/pages/metrics/report.ts

...
_Description_
_Description_
_Null_

ADM-669: [frontend] fix: fix e2e test

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-github.mdx

...
_Description_
_Description_
_Null_

ADM-717[docs]refactor: delete useless exception

---

backend/src/main/java/heartbeat/controller/pipeline/PipelineController.java
backend/src/main/java/heartbeat/controller/pipeline/dto/request/PipelineType.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/test/java/heartbeat/controller/pipeline/BuildKiteControllerTest.java
backend/src/test/java/heartbeat/controller/pipeline/dto/response/PipelineTypeTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java

...
_Description_
_Description_
_Null_

ADM-709[backend] feat: fix type not find error and add checktTime method

---

frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/pages/metrics/metrics.ts
frontend/cypress/pages/metrics/report.ts
frontend/src/components/Common/DateRangeViewer/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx
frontend/src/components/Metrics/ReportStep/style.tsx

...
_Description_
_Description_
_Null_

ADM-683: [frontend] test: update date picker test

---

frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/__tests__/src/hooks/useGetMetricsStepsEffect.test.tsx
frontend/cypress/pages/metrics/metrics.ts
frontend/src/constants/resources.ts
frontend/src/hooks/useGetMetricsStepsEffect.ts

...
_Description_
_Description_
_Null_

ADM-735: [frontend] fix: fix error message

---

backend/src/main/java/heartbeat/client/BuildKiteFeignClient.java
backend/src/main/java/heartbeat/controller/pipeline/PipelineController.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/test/java/heartbeat/controller/pipeline/BuildKiteControllerTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx

...
_Description_
_Description_
_Null_

ADM-709[backend][docs]: delete startTime and EndTime for buildKite

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/config/WebConfig.java
backend/src/main/java/heartbeat/controller/board/JiraController.java
backend/src/main/java/heartbeat/controller/board/dto/request/BoardType.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/controller/board/JiraControllerTest.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-708:[backend][docs]refactor: refactor get board info api

---

backend/src/main/java/heartbeat/controller/report/dto/response/MetricsDataCompleted.java
backend/src/main/java/heartbeat/controller/report/dto/response/ReportResponse.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/controller/report/GenerateReporterControllerTest.java
backend/src/test/java/heartbeat/controller/report/reportResponse.json
backend/src/test/java/heartbeat/handler/AsyncReportRequestHandlerTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

ADM-735:[backend] Fix rebase issue

---

frontend/__tests__/src/components/Common/NotificationButton/NotificationButton.test.tsx
frontend/cypress/pages/metrics/report.ts
frontend/src/components/Common/NotificationButton/index.tsx
frontend/src/components/Common/NotificationButton/style.tsx
frontend/src/constants/resources.ts
frontend/src/theme.ts

...
_Description_
_Description_
_Null_

ADM-669: [frontend] fix: fix DC issues

---

frontend/__tests__/src/components/Metrics/ReportButtonGroup.test.tsx
frontend/__tests__/src/fixtures.ts
frontend/src/clients/report/ReportClient.ts
frontend/src/clients/report/dto/response.ts
frontend/src/components/Common/ReportGrid/ReportCard/index.tsx
frontend/src/components/Metrics/ReportButtonGroup/index.tsx
frontend/src/components/Metrics/ReportStep/index.tsx

fix e2e issue
_Description_
_Description_
_Null_

[frontend]Adm 669: fix e2e issue

---

backend/src/main/java/heartbeat/config/WebConfig.java
backend/src/main/java/heartbeat/controller/pipeline/PipelineController.java
backend/src/main/java/heartbeat/controller/pipeline/dto/request/PipelineType.java
backend/src/main/java/heartbeat/controller/source/GithubController.java
backend/src/main/java/heartbeat/controller/source/SourceType.java
backend/src/test/java/heartbeat/controller/pipeline/dto/response/PipelineTypeTest.java
backend/src/test/java/heartbeat/controller/source/GithubControllerTest.java

...
_Description_
_Description_
_Null_

ADM-717[backend]refactor: put source and pipeline type to web config

---

backend/src/main/java/heartbeat/config/WebConfig.java
backend/src/main/java/heartbeat/controller/board/JiraController.java
backend/src/main/java/heartbeat/controller/board/dto/request/BoardType.java
backend/src/test/java/heartbeat/controller/board/JiraControllerTest.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-708:[backend]refactor: put source and board type to web config

---

frontend/package.json
frontend/pnpm-lock.yaml

Fix type-check for lint-staged

ADM-715:[Frontend] Fix type-check for lint-staged

---

frontend/__tests__/src/containers/ReportStep/DoraMetrics.test.tsx
frontend/src/containers/ReportStep/BoradMetrics/index.tsx
frontend/src/containers/ReportStep/DoraMetrics/index.tsx

fix loading issue, remove unused state
_Description_
_Description_
_Null_

ADM-699-fix: [frontend] fix loading issue, remove unused state

---

backend/src/main/java/heartbeat/service/report/GenerateReporterService.java

...
_Description_
_Description_
_Null_

ADM-735:[backend]fix: remove async exception ahead

---

backend/src/main/java/heartbeat/controller/board/JiraController.java
backend/src/main/java/heartbeat/controller/board/dto/request/BoardType.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-board.mdx

...
_Description_
_Description_
_Null_

ADM-708:[backend]fix: board verify throw base exception

---

backend/src/main/java/heartbeat/controller/source/GithubController.java
backend/src/main/java/heartbeat/controller/source/dto/VerifyBranchRequest.java
backend/src/test/java/heartbeat/controller/source/GithubControllerTest.java

...
_Description_
_Description_
_Null_

ADM-715[backend]feat: put branch in request body

---

backend/src/main/java/heartbeat/client/BuildKiteFeignClient.java
backend/src/main/java/heartbeat/config/CacheConfig.java

...
_Description_
_Description_
_Null_

ADM-675 [backend]: reduce TTL time to 90 second

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-github.mdx

...
_Description_
_Description_
_Null_

ADM-715[docs]refactor: put branch in request body

---

frontend/__tests__/src/hooks/useGenerateReportEffect.test.tsx
frontend/src/layouts/Header.tsx

fix browser back logic
_Description_
_Description_
_Null_

ADM-736: [frontend] fix: fix browser back logic

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/client/dto/pipeline/buildkite/CachePageService.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/CachePageService.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/CachePageServiceTest.java

...
_Description_
_Description_
_Null_

ADM-675[backend]: fix bug

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
frontend/cypress/e2e/createANewProject.cy.ts

Reverts au-heartbeat/Heartbeat#962
@weiraneve Please resolve e2e error

Revert "ADM-748:[backend]feat: add isRealDoneCardByHistory to get real done history"

---

backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
frontend/cypress/e2e/createANewProject.cy.ts
frontend/cypress/e2e/importAProject.cy.ts

...
_Description_
_Description_
_Null_

ADM-748:[backend]refactor: use Objects api

---

.github/workflows/BuildAndDeploy.yml
ops/check.sh

Try to reduce Jest log with silent in pipeline

ADM-715:[Frontend] try to reduce Jest log with silent

---

frontend/__tests__/components/HomeGuide/HomeGuide.test.tsx
frontend/__tests__/containers/MetricsStep/CycleTime.test.tsx
frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/containers/MetricsStep/RealDone.test.tsx
frontend/__tests__/context/metricsSlice.test.ts
frontend/__tests__/fixtures.ts
frontend/__tests__/utils/Util.test.tsx
frontend/src/components/HomeGuide/index.tsx
frontend/src/constants/fileConfig.ts
frontend/src/constants/resources.ts
frontend/src/containers/MetricsStep/Crews/AssigneeFilter.tsx
frontend/src/containers/MetricsStep/Crews/style.tsx
frontend/src/containers/MetricsStep/CycleTime/Table/CellAutoComplete.tsx
frontend/src/containers/MetricsStep/CycleTime/Table/index.tsx
frontend/src/containers/MetricsStep/CycleTime/Table/style.tsx
frontend/src/containers/MetricsStep/CycleTime/style.tsx
frontend/src/containers/MetricsStep/RealDone/index.tsx
frontend/src/containers/MetricsStepper/index.tsx
frontend/src/containers/ReportStep/BoardMetrics/index.tsx
frontend/src/context/Metrics/metricsSlice.ts
frontend/src/utils/util.ts

Reference: https://dorametrics.atlassian.net/browse/ADM-740
1. show options for cycle time settings
2. show corresponding table data for different types
3. save config with cycle time type, cycle time settings by column or by status
4. import config with new schema and compatible with old schema

[ADM-740] Add mapping configuration item in page metrics

---

frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/__tests__/context/metaSlice.test.ts
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/BranchSelection/index.tsx
frontend/src/context/meta/metaSlice.tsx

Fix the endless loading when branch name contain special character

ADM-715: [Frontend] fix error when branch name contain special character

---

frontend/cypress/e2e/createANewProject.cy.ts

...
_Description_
_Description_
_Null_

ADM-766: [frontend]fix e2e test

---

frontend/vite.config.ts

...
_Description_
_Description_
_Null_

[frontend]fix: change frontend to context localhost:4322

---

frontend/__tests__/containers/ConfigStep/Board.test.tsx
frontend/__tests__/fixtures.ts
frontend/src/constants/resources.ts
frontend/src/containers/ConfigStep/Board/index.tsx

rename error prompt，add an exclamation point at the end.
_Description_
_Description_
_Null_

ADM-778: [frontend] chore: rename error prompt

---

backend/src/main/java/heartbeat/handler/AsyncMetricsDataHandler.java
backend/src/main/java/heartbeat/handler/base/AsyncDataBaseHandler.java
backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
backend/src/test/java/heartbeat/handler/base/AsyncDataBaseHandlerTest.java

...
_Description_
_Description_
_Null_

ADM-733[backend]feat: add lock for file

---

ops/infra/Dockerfile.backend

...
_Description_
_Description_
_Null_

ADM-733[backend]feat: give app div permission in Dockerfile

---

ops/infra/docker-compose.yml

...
_Description_
_Description_
_Null_

ADM-733[frontend][backend]feat: delete container_name for backend

---

frontend/__tests__/containers/ReportStep/BoardMetrics.test.tsx
frontend/__tests__/containers/ReportStep/ReportDetail/board.test.tsx
frontend/src/components/Common/ReportForThreeColumns/index.tsx
frontend/src/components/Common/ReportGrid/ReportCard/index.tsx
frontend/src/components/Common/ReportGrid/ReportCard/style.tsx
frontend/src/components/ErrorMessagePrompt/index.tsx
frontend/src/components/ErrorMessagePrompt/style.tsx
frontend/src/constants/resources.ts
frontend/src/containers/ReportStep/BoardMetrics/index.tsx
frontend/src/containers/ReportStep/ReportDetail/board.tsx
frontend/src/containers/ReportStep/index.tsx
frontend/src/context/config/configSlice.ts

...
_Description_
_Description_
_Null_

ADM-763: [frontend] feat: handle only select classification error

---

ops/infra/docker-compose.yml

...
_Description_
_Description_
_Null_

ADM-733[backend]revert: expose ports to make e2e pass

---

ops/infra/docker-compose.yml

This reverts commit 61439aa693e52c2b0b72cba313210a56646de46a.
...
_Description_
_Description_
_Null_

Revert "ADM-733[backend]revert: expose ports to make e2e pass (#1007)"

---

frontend/src/components/Common/ReportForThreeColumns/index.tsx

...
_Description_
_Description_
_Null_

ADM-763: [frontend] refactor: refactor component

---

frontend/src/containers/MetricsStepper/index.tsx

highlight next button when the dropdown data is successfully obtained from the interface
_Description_
_Description_
_Null_

[frontend] ADM-781: fix isDeploymentFrequencyValid logic

---

frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/BranchSelection.test.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/BranchSelection/BranchChip/index.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/BranchSelection/index.tsx

...
_Description_
_Description_
_Null_

ADM-779: [Frontend] No need to verify branch when user select metrics without Github

---

ops/infra/Dockerfile.backend

...
_Description_
_Description_
_Null_

ADM-733[backend] feat: change mkdir file path

---

ops/infra/docker-compose.yml

...
_Description_
_Description_
_Null_

ADM-733[backend] feat: change docker-compose.yml to deploy

---

frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/__tests__/containers/ReportStep/ReportStep.test.tsx
frontend/__tests__/context/metricsSlice.test.ts
frontend/src/context/Metrics/metricsSlice.ts
frontend/src/context/interface/index.tsx
frontend/src/hooks/useMetricsStepValidationCheckContext.tsx

...
_Description_
_Description_
_Null_

ADM-762: [frontend] feat: clear cache in pipeline

---

docs/src/content/docs/en/devops/how-to-deploy-heartbeat-in-multiple-instances-by-k8s.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-733[docs] feat: creat deploy file guide how to deploy by k8s

---

backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java

...
_Description_
_Description_
_Null_

ADM-796:[backend]feat: set prLeadTime to 0 when commit is reverted

---

frontend/__tests__/context/configSlice.test.ts
frontend/__tests__/fixtures.ts
frontend/src/clients/report/ReportClient.ts
frontend/src/clients/report/dto/response.ts
frontend/src/containers/MetricsStepper/index.tsx
frontend/src/containers/ReportButtonGroup/index.tsx
frontend/src/containers/ReportStep/DoraMetrics/index.tsx
frontend/src/containers/ReportStep/ReportDetail/withBack.tsx
frontend/src/context/config/configSlice.ts

init step when back
_Description_
_Description_
_Null_

[frontend]ADM-781: init step when back

---

README.md
docs/src/content/docs/en/devops/how-to-deploy-heartbeat-in-multiple-instances-by-k8s.mdx
ops/infra/docker-compose.yml

...
_Description_
_Description_
_Null_

Adm 733[backend][stub]feat: update readme and docs

---

README.md
docs/src/content/docs/en/devops/how-to-deploy-heartbeat-in-multiple-instances-by-k8s.mdx

...
_Description_
_Description_
_Null_

ADM-733[docs] refactor: refactor K8s to K8S

---

frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/context/stepperSlice.test.ts
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx
frontend/src/containers/MetricsStep/index.tsx
frontend/src/context/stepper/StepperSlice.tsx
frontend/src/hooks/useGetPipelineToolInfoEffect.ts

...
_Description_
_Description_
_Null_

ADM-777:[frontend]feat: add should refresh state for board info load

---

README.md
docs/src/content/docs/en/spikes/tech-spikes-support-multiple-instances-for-backend-service.mdx

...
_Description_
_Description_
_Null_

Adm 733[docs]feat: change readme and spike docs

---

backend/src/main/java/heartbeat/controller/report/dto/request/GenerateReportRequest.java
backend/src/main/java/heartbeat/controller/report/dto/response/MetricsDataCompleted.java
backend/src/main/java/heartbeat/handler/AsyncMetricsDataHandler.java
backend/src/main/java/heartbeat/handler/base/AsyncDataBaseHandler.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/report/ReportService.java
backend/src/main/java/heartbeat/util/IdUtil.java
backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
backend/src/test/java/heartbeat/service/report/ReportServiceTest.java

… file to record metric status
...
_Description_
_Description_
_Null_

ADM-791:[backend]refactor: Resolve concurrency problem using separate file to record metric status

---

frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/DeploymentFrequencySettings.test.tsx
frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/index.tsx

fetch step api when init
_Description_
_Description_
_Null_

[frontend] ADM-718: fetch step api when init

---

frontend/__tests__/containers/MetricsStep/CycleTime.test.tsx
frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/containers/MetricsStep/RealDone.test.tsx
frontend/__tests__/containers/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/context/metricsSlice.test.ts
frontend/src/containers/MetricsStep/CycleTime/Table/index.tsx
frontend/src/containers/MetricsStepper/index.tsx
frontend/src/context/Metrics/metricsSlice.ts

reset cycle time settings when back
_Description_
_Description_
_Null_

ADM-765 [frontend] fix: reset cycle time settings when back

---

frontend/src/clients/report/dto/response.ts
frontend/src/constants/resources.ts
frontend/src/containers/ReportStep/BoardMetrics/index.tsx
frontend/src/containers/ReportStep/DoraMetrics/index.tsx

reconstruction of the logic of show more
_Description_
_Description_
_Null_

ADM-805: [frontend] chore: reconstruction of the logic of show moreAdm 805

---

frontend/__tests__/containers/ConfigStep/MetricsTypeCheckbox.test.tsx
frontend/src/constants/resources.ts
frontend/src/containers/ConfigStep/BasicInfo/RequiredMetrics/index.tsx
frontend/src/containers/MetricsStep/Classification/index.tsx
frontend/src/context/config/configSlice.ts

Reference: https://dorametrics.atlassian.net/browse/ADM-804
should check 'all' when import json with 7 metrics

[ADM-804] should check 'all' when import json with 7 metrics

---

frontend/__tests__/context/configSlice.test.ts
frontend/src/containers/ConfigStep/BasicInfo/RequiredMetrics/index.tsx
frontend/src/context/config/configSlice.ts

https://dorametrics.atlassian.net/browse/ADM-804
if metrics in config file have some invalid input, it will also show in selection
only show metrics in required data
_Null_

[ADM-804][Frontend] only show metrics in required data

---

frontend/e2e/pages/metrics/ReportStep.ts
frontend/e2e/specs/import-project-from-file.spec.ts
frontend/e2e/utils/download.ts

...
_Description_
_Description_
_Null_

ADM-808 check download for import

---

backend/src/main/java/heartbeat/client/dto/board/jira/Sprint.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

Adm 772[backend]add 'status date' column in board data

---

backend/src/main/java/heartbeat/service/report/KanbanCsvService.java

...
_Description_
_Description_
_Null_

ADM-772:[backend]fix: fix TODO is confusion question

---

backend/src/main/java/heartbeat/client/JiraFeignClient.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-829:[backend]fix: delete bad checkSite api

---

backend/build.gradle
backend/src/test/java/heartbeat/service/report/KanbanCsvServiceTest.java

add test to repair coverage verification

add-test:[backend]fix: add test for KanbanCsvService

---

frontend/src/context/Metrics/metricsSlice.ts

...
_Description_
_Description_
_Null_

ADM-829[frontend]fix: make PipelineCrews not null in create project

---

backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/resources/log4j2.xml

...
_Description_
_Description_
_Null_

ADM-819 mask sensitive data in log message

---

frontend/e2e/fixtures/createNew/metricsStep.ts

...
_Description_
_Description_
_Null_

ADM-813:[frontend]fix: fix e2e testing

---

backend/src/main/java/heartbeat/handler/AsyncMetricsDataHandler.java
backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
frontend/src/containers/MetricsStep/Advance/Advance.tsx

...
_Description_
_Description_
_Null_

ADM-813: [frontend]: fix UI

---

frontend/src/containers/MetricsStep/Advance/Advance.tsx

...
_Description_
_Description_
_Null_

ADM-813: [frontend]: fix advanced settings link

---

frontend/src/containers/MetricsStep/Advance/Advance.tsx

...
_Description_
_Description_
_Null_

ADM-813:[frontend]fix the url

---

docs/src/content/docs/en/spikes/tech-spikes-github-graphql-api-about-replacing-existing-rest-api.mdx

...
_Description_
_Description_
_Null_

ADM-677[docs]feat: add curl for api

---

.github/workflows/build-and-deploy.yml

...
_Description_
If applicable, add screenshots to help explain the behavior of your code.
_Description_
_Null_

fix: config frontend for coverage

---

frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
frontend/src/constants/resources.ts
frontend/src/containers/MetricsStep/index.tsx

...
_Description_
_Description_
_Null_

ADM-831:[frontend]feat: add pipeline is future time check

---

frontend/e2e/pages/metrics/MetricsStep.ts
frontend/e2e/specs/page-jumps.spec.ts

fix e2e test
_Description_
_Description_
_Null_

ADM-767 [frontend] test: fix e2e test

---

frontend/src/containers/MetricsStepper/index.tsx

ADM-841: [frontend] fix: fix next button display logic
_Description_
_Description_
_Null_

ADM-841: [frontend] fix: fix next button display logic

---

ops/deploy.sh

...
_Description_
_Description_
_Null_

fix: put swagger host in the env[backend]

---

frontend/src/clients/board/dto/request.ts
frontend/src/containers/ConfigStep/DateRangePicker/index.tsx
frontend/src/hooks/useVerifyBoardEffect.ts

...
_Description_
_Description_
_Null_

Adm-839[frontend]fix change time then board & pipeline configuration reload

---

backend/build.gradle
backend/sonar-project.properties

Sonar ignore 1

---

backend/build.gradle

...
_Description_
```java
violationRules {
rule {
limit {
counter = 'INSTRUCTION'
value = 'COVEREDRATIO'
minimum = 1.0
}
}
rule {
limit {
counter = 'LINE'
value = 'COVEREDRATIO'
minimum = 1.0
}
}
rule {
limit {
counter = 'METHOD'
value = 'COVEREDRATIO'
minimum = 1.0
}
}
rule {
limit {
counter = 'BRANCH'
value = 'COVEREDRATIO'
minimum = 0.90
}
}
rule {
limit {
counter = 'CLASS'
value = 'COVEREDRATIO'
minimum = 1.0
}
}
}```
_Null_

pref(sonar): update UT coverage

---

frontend/__tests__/containers/ConfigStep/DateRangePicker.test.tsx
frontend/src/containers/ConfigStep/DateRangePicker/index.tsx

...
_Description_
_Description_
_Null_

ADM-839[frontend]fix reload pipeline config

---

frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/DeploymentFrequencySettings.test.tsx
frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
frontend/src/constants/resources.ts
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/index.tsx
frontend/src/containers/MetricsStep/index.tsx

...
_Description_
_Description_
_Null_

ADM-831:[frontend]feat: add future time check for metrics step

---

frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx
frontend/src/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx

...
_Description_
_Description_
_Null_

ADM-831:[frontend]feat: update pipeline no step logic

---

frontend/__tests__/containers/ConfigStep/SourceControl.test.tsx
frontend/src/containers/ConfigStep/SourceControl/index.tsx

...
_Description_
_Description_
_Null_

ADM-839[frontend]fix reload pipeline config when reset source control

---

frontend/__tests__/containers/ConfigStep/DateRangePicker.test.tsx
frontend/src/containers/ConfigStep/DateRangePicker/index.tsx

...
_Description_
_Description_
_Null_

ADM-839[frontend]fix next button when no jira card

---

.github/workflows/build-and-deploy.yml

Slack notification

---

backend/src/main/java/heartbeat/client/decoder/BuildKiteFeignClientDecoder.java
backend/src/main/java/heartbeat/client/decoder/GitHubFeignClientDecoder.java
backend/src/main/java/heartbeat/client/decoder/JiraFeignClientDecoder.java
backend/src/test/java/heartbeat/decoder/BuildKiteFeignClientDecoderTest.java
backend/src/test/java/heartbeat/decoder/GitHubFeignClientDecoderTest.java
backend/src/test/java/heartbeat/decoder/JiraFeignClientDecoderTest.java

...
_Description_
_Description_
_Null_

ADM-856:[backend]feat: update all feign clients decoder error message

---

frontend/__tests__/containers/MetricsStep/CycleTime.test.tsx
frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/containers/MetricsStep/reworkSettings.test.tsx
frontend/__tests__/fixtures.ts
frontend/src/components/Common/MultiAutoComplete/index.tsx
frontend/src/constants/resources.ts
frontend/src/containers/MetricsStep/Advance/Advance.tsx
frontend/src/containers/MetricsStep/Advance/style.tsx
frontend/src/containers/MetricsStep/CycleTime/index.tsx
frontend/src/containers/MetricsStep/CycleTime/style.tsx
frontend/src/containers/MetricsStep/ReworkSettings/index.tsx
frontend/src/containers/MetricsStep/ReworkSettings/style.tsx
frontend/src/containers/MetricsStep/index.tsx
frontend/src/containers/MetricsStep/style.tsx

rename setting and fix style
_Description_
_Description_
_Null_

ADM-691: [frontend] fix: rename setting and fix style

---

frontend/e2e/fixtures/index.ts
frontend/e2e/pages/metrics/ReportStep.ts
frontend/playwright.config.ts

...
_Description_
_Description_
_Null_

chore: extend the overall timeout of e2e 1 more minute.

---

frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
frontend/__tests__/containers/ReportStep/ReportStep.test.tsx
frontend/__tests__/fixtures.ts
frontend/src/clients/report/ReportClient.ts
frontend/src/clients/report/dto/request.ts
frontend/src/clients/report/dto/response.ts
frontend/src/constants/resources.ts
frontend/src/containers/MetricsStep/Advance/style.tsx
frontend/src/containers/MetricsStep/CycleTime/index.tsx
frontend/src/containers/MetricsStep/CycleTime/style.tsx
frontend/src/containers/MetricsStep/ReworkSettings/index.tsx
frontend/src/containers/ReportStep/BoardMetrics/index.tsx

add request fields
_Description_
_Description_
_Null_

ADM-691: [frontend] fix: add request fields

---

frontend/src/clients/report/dto/request.ts
frontend/src/containers/ReportStep/BoardMetrics/index.tsx
frontend/src/hooks/useGenerateReportEffect.ts

fix sonar issue
_Description_
_Description_
_Null_

ADM-691: [frontend] fix: fix sonar issue

---

.github/workflows/build-and-deploy.yml

...
_Description_
_Description_
_Null_

ADM-857: [backend] test: test

---

frontend/src/containers/ConfigStep/PipelineTool/index.tsx
frontend/src/containers/ConfigStep/SourceControl/index.tsx
frontend/src/hooks/useVerifyBoardEffect.ts

hidden alert when reset
_Description_
_Description_
_Null_

[frontend][ADM-793] feat: hidden alert when reset

---

.github/workflows/build-and-deploy.yml

Reverts au-heartbeat/Heartbeat#1169

Revert "Adm 857 w"

---

.github/workflows/build-and-deploy.yml

...
_Description_
_Description_
_Null_

ADM-857:[backend]refactor: test

---

backend/src/main/java/heartbeat/handler/base/AsyncDataBaseHandler.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/CachePageService.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/handler/AsyncExceptionHandlerTest.java
backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/CachePageServiceTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

...
_Description_
_Description_
_Null_

ADM-851:[backend] fix: fix sonar for security issues

---

.github/workflows/build-and-deploy.yml
ops/check.sh

...
_Description_
_Description_
_Null_

ADM-857:[backend]feat: add check buildkite status

---

README.md

...
_Description_
_Description_
_Null_

ADM-857:[backend]docs: add a space

---

.github/workflows/build-and-deploy.yml
ops/check.sh

...
_Description_
_Description_
_Null_

fix buildkite check before merging PR

---

.buildkite/pipeline.yml
.github/workflows/build-and-deploy.yml
ops/check.sh

...
_Description_
_Description_
_Null_

Buildkite e2e deployment check

---

.github/workflows/build-and-deploy.yml

...
_Description_
_Description_
_Null_

enable main branch to deploy e2e every time

---

docs/src/content/docs/en/designs/optimize-generate-report.mdx
frontend/src/containers/ReportStep/BoardMetrics/index.tsx

fix e2e
_Description_
_Description_
_Null_

ADM-692: [frontend] fix: fix e2e

---

frontend/src/clients/report/dto/request.ts
frontend/src/containers/ReportStep/BoardMetrics/index.tsx

fix e2e issue
_Description_
_Description_
_Null_

ADM-692: [frontend] fix: fix e2e issue

---

frontend/src/containers/MetricsStep/ReworkSettings/ReworkDialog/index.tsx
frontend/src/containers/MetricsStep/ReworkSettings/ReworkDialog/style.tsx

enhance style for step
_Description_
_Description_
_Null_

[frontend] ADM-774: enhance style for step

---

frontend/src/containers/MetricsStep/style.tsx

add pointer style
_Description_
_Description_
_Null_

[frontend]ADM-774: add pointer style

---

backend/build.gradle

Reverts au-heartbeat/Heartbeat#1260

Revert "fix(deps): update dependency org.springframework.cloud:spring-cloud-starter-openfeign to v4.1.0"[backend]

---

frontend/__tests__/constants/fileConfig/fileConfig.test.ts
frontend/__tests__/containers/MetricsStep/MultiAutoComplete.test.tsx
frontend/__tests__/containers/MetricsStepper/MetricsStepper.test.tsx
frontend/__tests__/context/metricsSlice.test.ts
frontend/__tests__/fixtures.ts
frontend/e2e/fixtures/createNew/metricsStep.ts
frontend/e2e/fixtures/importFile/add-flag-as-block-config-file.ts
frontend/e2e/fixtures/importFile/multiple-done-config-file.ts
frontend/e2e/pages/metrics/MetricsStep.ts
frontend/src/components/Common/MultiAutoComplete/index.tsx
frontend/src/constants/fileConfig.ts
frontend/src/containers/MetricsStep/CycleTime/Table/index.tsx
frontend/src/containers/MetricsStep/ReworkSettings/index.tsx
frontend/src/containers/MetricsStep/index.tsx
frontend/src/containers/MetricsStepper/index.tsx
frontend/src/containers/ReportStep/BoardMetrics/index.tsx
frontend/src/context/Metrics/metricsSlice.ts

reset rework setting when user revalidate or reselect time
_Description_
_Description_
_Null_

ADM-864: [frontend] fix: reset rework setting when user revalidate or reselect time

---

frontend/src/containers/MetricsStep/index.tsx

…idate or reselect time"
reset rework setting when user revalidate or reselect time
...
_Description_
_Description_
_Null_

Revert ADM-864: [frontend] fix: reset rework setting when user revalidate or reselect time

---

.buildkite/pipeline.yml
ops/check.sh

...
_Description_
_Description_
_Null_

Reduce check time onBuildkite 

---

backend/src/main/java/heartbeat/controller/board/dto/response/JiraCardDTO.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java

...
_Description_
_Description_
_Null_

ADM-693-fix [backend]: fix bug

---

frontend/package.json
frontend/pnpm-lock.yaml

Reverts au-heartbeat/Heartbeat#1295

Revert "chore(deps): update dependency @dotenvx/dotenvx to ^0.27.0"

---

frontend/src/clients/pipeline/PipelineToolClient.ts
frontend/src/clients/sourceControl/SourceControlClient.ts
frontend/src/errors/BadRequestError.ts
frontend/src/errors/ErrorType.ts
frontend/src/errors/ForbiddenError.ts
frontend/src/errors/InternalServerError.ts
frontend/src/errors/NotFoundError.ts
frontend/src/errors/TimeoutError.ts
frontend/src/errors/UnauthorizedError.ts
frontend/src/errors/UnknownError.ts
frontend/src/errors/index.ts
frontend/src/hooks/useVerifyBoardEffect.ts
renovate.json

...
_Description_
_Description_
_Null_

refactor(error): rename heartbeatError to appError

---

backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
frontend/src/containers/ReportStep/BoardMetrics/index.tsx

fix: null point error
fix: do not show rework module when board mapping only select done status
_Null_

ADM-903-fix:[backend][frontend] fix: fix null point error

---

README.md

...
_Description_
_Description_
_Null_

ADM-865:update readme doc

---

frontend/src/containers/ReportStep/BoardMetrics/index.tsx

fix show more button display logic
_Description_
_Description_
_Null_

ADM-903: [frontend] fix: fix show more button display logic

---

backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java

...
_Description_
_Description_
_Null_

ADM-865:[backend] feat: add new exception for Permission Deny

---

docs/src/content/docs/en/spikes/tech-spikes-split-verification-of-github.mdx

...
_Description_
_Description_
_Null_

ADM-865[docs] feat: add new exception

---

frontend/src/containers/MetricsStepper/index.tsx

...
_Description_
_Description_
_Null_

ADM-865:[frontend]fix click next button logic

---

backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java

...
_Description_
_Description_
_Null_

ADM-873:[backend] fix: fix test

---

frontend/src/containers/MetricsStep/TokenAccessAlert/index.tsx

...
_Description_
_Description_
_Null_

ADM-865:[frontend] fix alert

---

docs/src/content/docs/en/spikes/tech-spikes-chart-api-solutions.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-886:[docs]docs: add chart API spike

---

frontend/__tests__/containers/MetricsStep/TokenAccessAlert.test.tsx
frontend/src/containers/MetricsStep/TokenAccessAlert/index.tsx

...
_Description_
_Description_
_Null_

ADM-865:[frontend]replace http status code

---

docs/src/content/docs/en/spikes/tech-spikes-chart-api-solutions.mdx

...
_Description_
_Description_
_Null_

ADM-886:[docs]docs: refactor chart API docs sequence diagram

---

.github/workflows/Release.yaml
.gitignore

...
_Description_
_Description_
_Null_

chore(sbom): generate sbom when releasing

---

frontend/e2e/fixtures/input-files/add-flag-as-block-config-file.template.json

...
E2E-Test-For-Flag-Block
E2E-Test-For-Flag-As-Block
_Null_

ADM-890:[docs] docs: rename project

---

ops/check.sh

...
_Description_
_Description_
_Null_

ADM-920 feat: extension sleep time

---

backend/src/main/java/heartbeat/client/BuildKiteFeignClient.java
backend/src/main/java/heartbeat/client/dto/pipeline/buildkite/PageBuildKitePipelineInfoDTO.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java
backend/src/main/java/heartbeat/service/pipeline/buildkite/CachePageService.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/CachePageServiceTest.java

...
_Description_
_Description_
_Null_

Adm 920[backend] feat: Support to retrieve multiple pages of pipelines in metrics page

---

backend/build.gradle

Reverts au-heartbeat/Heartbeat#1390

Revert [backend]"fix(deps): update dependency org.springframework.cloud:spring-cloud-starter-openfeign to v4.1.1"

---

frontend/__tests__/hooks/useGetMetricsStepsEffect.test.tsx

improve test covarage
_Description_
_Description_
_Null_

ADM-913: [frontend] fix: improve test covarage

---

backend/src/main/java/heartbeat/handler/AsyncExceptionHandler.java
backend/src/main/java/heartbeat/handler/AsyncMetricsDataHandler.java
backend/src/main/java/heartbeat/handler/AsyncReportRequestHandler.java
backend/src/main/java/heartbeat/handler/base/AsyncDataBaseHandler.java
backend/src/test/java/heartbeat/handler/AsyncReportRequestHandlerTest.java
backend/src/test/java/heartbeat/handler/base/AsyncDataBaseHandlerTest.java

fix security issue according sonar
_Null_

fix security issue according sonar

---

frontend/e2e/pages/metrics/config-step.ts

...
_Description_
_Description_
_Null_

[ADM-887] fix: adjust the aria-label selector to fix the e2e test.

---

frontend/e2e/pages/metrics/config-step.ts

...
_Description_
_Description_
_Null_

[ADM-887]: adjust unique selector to fix the e2e.

---

frontend/scripts/generate-config-files.sh

add mapping in generate config file
_Description_
_Description_
_Null_

ADM-926-fix:[frontend] fix: add mapping in generate config file

---

frontend/__tests__/containers/ReportStep/ReportStep.test.tsx
frontend/src/containers/ReportStep/index.tsx

Adm-879-fix [frontend]: fix the notification close logic
_Description_
_Description_
_Null_

Adm-879-fix [frontend]: fix the notification close logic

---

backend/src/main/java/heartbeat/handler/base/AsyncDataBaseHandler.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/test/java/heartbeat/handler/AsyncExceptionHandlerTest.java
backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
backend/src/test/java/heartbeat/handler/AsyncReportRequestHandlerTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
frontend/src/clients/HttpClient.ts

It will jump to error page when user export csv. after several minutes
Every 5 mins all files will be deleted.
All files will be deleted when it expires after 30 mins.

ADM-940 [frontend][backend]: fix the report file bug

---

frontend/src/containers/ReportStep/style.tsx

ADM-938-style [frontend]: fix style
_Description_
_Description_
_Null_

ADM-938-style [frontend]: fix style

---

frontend/src/containers/ReportStep/style.tsx

ADM-938-e2e [frontend]: fix style
_Description_
_Description_
_Null_

ADM-938-e2e [frontend]: fix style

---

frontend/__tests__/components/Common/DateRangeViewer/DateRangeViewer.test.tsx
frontend/src/components/Common/DateRangeViewer/index.tsx
frontend/src/components/Common/DateRangeViewer/style.tsx
frontend/src/context/stepper/StepperSlice.tsx
frontend/src/hooks/useGenerateReportEffect.ts
frontend/src/hooks/useGetBoardInfo.ts
frontend/src/hooks/useGetMetricsStepsEffect.ts
frontend/src/hooks/useGetPipelineToolInfoEffect.ts

ADM-938-latest [frontend]: fix dc issues
_Description_
_Description_
_Null_

ADM-938-latest [frontend]: fix dc issues

---

frontend/src/constants/resources.ts
frontend/src/containers/ReportStep/DownloadDialog/style.tsx

fix dialog style
_Description_
_Description_
_Null_

ADM-924: [frontend] fix: fix dialog style

---

frontend/src/hooks/useGenerateReportEffect.ts

Adm 938 fe [frontend]: fix field
_Description_
_Description_
_Null_

Adm 938 fe [frontend]: fix field

---

frontend/src/components/Common/DateRangeViewer/index.tsx
frontend/src/constants/commons.ts
frontend/src/containers/MetricsStep/index.tsx
frontend/src/containers/ReportStep/index.tsx
frontend/src/context/stepper/StepperSlice.tsx

fix date range sort
_Description_
_Description_
_Null_

ADM-908:[frontend]fix: fix date range sort

---

frontend/__tests__/containers/ConfigStep/Board.test.tsx
frontend/__tests__/containers/ConfigStep/PipelineTool.test.tsx
frontend/__tests__/containers/ConfigStep/SourceControl.test.tsx
frontend/__tests__/fixtures.ts
frontend/e2e/pages/metrics/config-step.ts
frontend/src/containers/ConfigStep/Board/index.tsx
frontend/src/containers/ConfigStep/FormAlert/index.tsx
frontend/src/containers/ConfigStep/FormAlert/style.tsx

...
_Description_
_Description_
_Null_

ADM-744:[frontend]feat: update board verify failed state judge

---

frontend/__tests__/containers/ConfigStep/Board.test.tsx
frontend/__tests__/fixtures.ts
frontend/src/containers/ConfigStep/Board/index.tsx

...
_Description_
_Description_
_Null_

ADM-744:[frontend]feat: add alert visible handle logic

---

frontend/jest.config.json

pref(enum): speed up the test in local env[frontend]

---

frontend/src/hooks/useGenerateReportEffect.ts

...
_Description_
_Description_
_Null_

ADM-955: [frontend] feat: fix gainPollingUrl error

---

frontend/__tests__/containers/ReportStep/style.test.tsx
frontend/src/App.css
frontend/src/App.tsx
frontend/src/containers/MetricsStep/style.tsx
frontend/src/containers/MetricsStepper/style.tsx
frontend/src/containers/ReportButtonGroup/style.tsx
frontend/src/containers/ReportStep/ChartAndTitleWrapper/index.tsx
frontend/src/containers/ReportStep/ChartAndTitleWrapper/style.tsx
frontend/src/containers/ReportStep/ReportDetail/withBack.tsx
frontend/src/containers/ReportStep/index.tsx
frontend/src/containers/ReportStep/style.tsx
frontend/src/theme.ts

...
_Description_
_Description_
_Null_

Adm-935 [frontend] Implement responsive chartings

---

frontend/README.md
frontend/src/containers/MetricsStepper/style.tsx
frontend/src/containers/ReportButtonGroup/style.tsx
frontend/src/containers/ReportStep/ChartAndTitleWrapper/style.tsx
frontend/src/containers/ReportStep/style.tsx

1. adjust some small style for charting responsibility according to DC  feedback 
2. readme upadte
...
_Description_
_Description_
_Null_

Adm-935 [frontend] adjust some small style for charting responsibility according to DC  feedback 

---

README.md
backend/src/main/java/heartbeat/service/report/VietnamHoliday.java
backend/src/test/java/heartbeat/service/report/VietnamHolidayTest.java
frontend/src/containers/ConfigStep/BasicInfo/index.tsx
frontend/src/containers/ConfigStep/BasicInfo/style.tsx

1. Add Readme
2. Adjust some style
3. Fix vietnam national holiday logic
_Description_
_Description_
_Null_

ADM-952 [frontend][backend] adjust according to DC

---

README.md

...
_Description_
_Description_
_Null_

ADM-952 [frontend] update readme image source

---

backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java
backend/src/test/java/heartbeat/service/report/CSVFileGeneratorTest.java
frontend/src/components/Common/ReportForDeploymentFrequency/index.tsx
frontend/src/components/Common/ReportForTwoColumns/index.tsx

...
_Description_
_Description_
_Null_

ADM-972 [frontend][backend]: fix dc issues

---

README.md
backend/src/main/resources/application.yml

...
_Description_
_Description_
_Null_

ADM-981 [docx]: change the readme

---

frontend/e2e/pages/metrics/config-step.ts
frontend/e2e/specs/major-path/cycle-time-by-status-test.spec.ts
frontend/e2e/specs/major-path/import-project-from-file.spec.ts
frontend/e2e/specs/major-path/page-jumps.spec.ts
frontend/e2e/specs/side-path/charting-unhappy-path.spec.ts
frontend/e2e/specs/side-path/unhappy-path.spec.ts
frontend/src/containers/ConfigStep/Board/index.tsx
frontend/src/containers/ConfigStep/PipelineTool/index.tsx
frontend/src/containers/ConfigStep/SourceControl/index.tsx

...
_Description_
_Description_
_Null_

ADM-974 [frontend]: auto verify when user import config file

---

backend/src/test/java/heartbeat/controller/report/ReporterControllerTest.java
backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java
backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/CachePageServiceTest.java
backend/src/test/java/heartbeat/service/report/CycleTimeCalculatorTest.java
frontend/src/clients/HttpClient.ts

...
_Description_
_Description_
_Null_

ADM-974 [frontend][backend]: fix sonar issue

---

README.md
frontend/e2e/pages/metrics/report-step.ts
frontend/e2e/specs/major-path/import-project-from-file.spec.ts

...
_Description_
_Description_
_Null_

ADM 973 [frontent] add readme and remove not supported e2e test temporarily

---

backend/src/main/java/heartbeat/repository/FileRepository.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/report/scheduler/DeleteExpireCSVScheduler.java
backend/src/main/resources/application.yml
backend/src/test/java/heartbeat/controller/report/ReporterControllerTest.java
backend/src/test/java/heartbeat/repository/FileRepositoryTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
backend/src/test/java/heartbeat/service/report/ReportServiceTest.java

...
_Description_
_Description_
_Null_

ADM-976 [backend]: fix dc issues that we will change expired times to yml

---

frontend/src/layouts/ShareReportTrigger/index.tsx
frontend/src/layouts/ShareReportTrigger/style.tsx

...
_Description_
_Description_
_Null_

ADM-973 [frontend] update style

---

frontend/src/layouts/ShareReportTrigger/index.tsx

...
_Description_
_Description_
_Null_

ADM-973: [frontend] reset component status when show share icon

---

backend/src/main/java/heartbeat/client/CalendarFeignClient.java
backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/java/heartbeat/controller/report/ReportController.java
backend/src/main/java/heartbeat/repository/FileRepository.java
backend/src/main/java/heartbeat/service/report/GenerateReporterService.java
backend/src/main/java/heartbeat/service/report/ReportService.java
backend/src/main/java/heartbeat/service/report/VietnamHoliday.java
backend/src/main/java/heartbeat/service/report/scheduler/DeleteExpireCSVScheduler.java
backend/src/main/resources/application-e2e.yml
backend/src/main/resources/application-local.yml
backend/src/main/resources/application.yml
backend/src/test/java/heartbeat/repository/FileRepositoryTest.java
backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
backend/src/test/java/heartbeat/service/report/ReportServiceTest.java
backend/src/test/java/heartbeat/service/report/VietnamHolidayTest.java
backend/src/test/resources/application-test.yml

...
_Description_
_Description_
_Null_

ADM-987 [backend]: adjust the logs for share

---

frontend/__tests__/containers/ReportStep/ReportDetail/board.test.tsx
frontend/__tests__/containers/ReportStep/ReportDetail/dora.test.tsx
frontend/__tests__/containers/ReportStep/ReportDetail/withBack.test.tsx
frontend/src/containers/MetricsStep/style.tsx
frontend/src/containers/ReportStep/DoraMetricsChart/PipelineSelector/index.tsx
frontend/src/containers/ReportStep/ReportContent/index.tsx
frontend/src/containers/ReportStep/ReportDetail/style.tsx
frontend/src/containers/ReportStep/ReportDetail/withBack.tsx
frontend/src/containers/ShareReport/index.tsx

...
_Description_
_Description_
_Null_

ADM-975 [frontend]: fix cr comment

---

README.md

...
_Description_
_Description_
_Null_

ADM-980 update readme

---

README.md
frontend/__tests__/containers/MetricsStep/Classification.test.tsx
frontend/e2e/pages/metrics/metrics-step.ts
frontend/src/containers/MetricsStep/Classification/index.tsx

...
_Description_
_Description_
_Null_

ADM-980 [frontend] rename label and do not show all option when option is more than 4

---

frontend/e2e/pages/metrics/metrics-step.ts
frontend/src/containers/MetricsStep/Classification/index.tsx
frontend/src/context/Metrics/metricsSlice.ts

...
_Description_
_Description_
_Null_

ADM-980: [frontend] fix e2e test after change the all option logic

---

README.md
frontend/src/containers/ReportStep/BoardMetricsChart/ClassificationChart/index.tsx

...
_Description_
_Description_
_Null_

ADM-984 [frontend]: add the yAxis for reversed bar chart

---

frontend/__tests__/components/Common/ReportGrid/DoraMetricsDialog.test.tsx
frontend/src/components/Common/ReportGrid/ReportCard/DoraMetricsDialog/index.tsx

...
_Description_
_Description_
_Null_

ADM-983 [frontend]: fix the bug of undefined

---

README.md
frontend/src/constants/resources.ts

...
_Description_
_Description_
_Null_

ADM-983 [frontend]: fix test issues

---

backend/src/main/java/heartbeat/controller/board/dto/response/StepsDay.java
backend/src/main/java/heartbeat/controller/report/dto/response/BoardCSVConfigEnum.java
backend/src/main/java/heartbeat/service/board/jira/JiraService.java
backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java
backend/src/main/java/heartbeat/service/report/KanbanCsvService.java
backend/src/test/java/heartbeat/service/report/BoardCsvFixture.java
backend/src/test/java/heartbeat/service/report/CSVFileGeneratorTest.java
backend/src/test/java/heartbeat/service/report/KanbanCsvServiceTest.java

...
_Description_
_Description_
_Null_

ADM-995 [backend]: modify the analysis column in the board csv file and fix test

---

README.md
frontend/__tests__/containers/ConfigStep/Board.test.tsx
frontend/__tests__/containers/ConfigStep/ConfigStep.test.tsx
frontend/__tests__/containers/ConfigStep/PipelineTool.test.tsx
frontend/__tests__/containers/ConfigStep/ResetConfirmDialog.test.tsx
frontend/__tests__/containers/ConfigStep/SourceControl.test.tsx
frontend/e2e/pages/metrics/config-step.ts
frontend/src/containers/ConfigStep/Board/index.tsx
frontend/src/containers/ConfigStep/PipelineTool/index.tsx
frontend/src/containers/ConfigStep/ResetConfirmDialog/index.tsx
frontend/src/containers/ConfigStep/ResetConfirmDialog/style.tsx
frontend/src/containers/ConfigStep/SourceControl/index.tsx
frontend/src/containers/ConfigStep/index.tsx

...
_Description_
_Description_
_Null_

ADM-990 [frontend]: add reset dialog when clicking the reset button

---

README.md

...
_Description_
_Description_
_Null_

ADM-990 [frontend]: change readme

---

README.md
frontend/src/containers/ConfigStep/ResetConfirmDialog/index.tsx
frontend/src/containers/MetricsStepper/ConfirmDialog/index.tsx

...
_Description_
_Description_
_Null_

ADM-990 [frontend]: modify the style about the cancel button

---

frontend/src/containers/ReportStep/ChartAndTitleWrapper/style.tsx

...
_Description_
_Description_
_Null_

ADM-992 [frontend]: change the style when device is mobile

---

README.md
backend/src/main/java/heartbeat/controller/pipeline/PipelineController.java
backend/src/main/java/heartbeat/controller/pipeline/dto/request/PipelineType.java
backend/src/main/java/heartbeat/controller/pipeline/dto/request/TokenParam.java
backend/src/test/java/heartbeat/controller/pipeline/BuildKiteControllerTest.java
backend/src/test/java/heartbeat/controller/pipeline/dto/response/PipelineTypeTest.java
frontend/__tests__/containers/ConfigStep/ConfigStep.test.tsx
frontend/__tests__/containers/ConfigStep/PipelineTool.test.tsx
frontend/e2e/fixtures/input-files/select-none-in-pipeline-tool-configuration.template.json
frontend/e2e/pages/metrics/config-step.ts
frontend/e2e/specs/major-path/import-project-from-file.spec.ts
frontend/e2e/specs/side-path/config-select-one-metrics.spec.ts
frontend/scripts/generate-config-files.sh
frontend/src/constants/resources.ts
frontend/src/containers/ConfigStep/Form/FormSelect.tsx
frontend/src/containers/ConfigStep/Form/literal.ts
frontend/src/containers/ConfigStep/PipelineTool/index.tsx
frontend/src/containers/MetricsStepper/index.tsx

...
_Description_
_Description_
_Null_

ADM-998 [frontend][backend]: add none option when dora metric select only lead time for changes

---

README.md

...
_Description_
_Description_
_Null_

ADM-998 [docs][frontend]: update readme

---

docs/src/content/docs/en/spikes/tech-spikes-github-api-for-pull-request-info-by-token.mdx
docs/src/i18n/en/nav.ts

...
_Description_
_Description_
_Null_

ADM-1001 [docs]: add github spike

---

frontend/e2e/pages/metrics/report-step.ts

...
_Description_
_Description_
_Null_

ADM-1001 [frontend]: try to fix the e2e test issue in the buildkite

---

README.md
frontend/__tests__/context/configSlice.test.ts
frontend/__tests__/hooks/useGetSourceControlConfigurationBranchEffect.test.tsx
frontend/__tests__/hooks/useGetSourceControlConfigurationCrewEffect.test.tsx
frontend/__tests__/hooks/useGetSourceControlConfigurationRepoEffect.test.tsx
frontend/e2e/fixtures/import-file/chart-step-data.ts
frontend/e2e/fixtures/input-files/charting-unhappy-path-config-file.template.json
frontend/e2e/pages/metrics/metrics-step.ts
frontend/src/containers/MetricsStep/SouceControlConfiguration/SourceControlMetricSelection/index.tsx
frontend/src/context/Metrics/metricsSlice.ts
frontend/src/hooks/useGetSourceControlConfigurationBranchEffect.tsx
frontend/src/hooks/useGetSourceControlConfigurationCrewEffect.tsx
frontend/src/hooks/useGetSourceControlConfigurationOrganizationEffect.tsx
frontend/src/hooks/useGetSourceControlConfigurationRepoEffect.tsx
frontend/src/hooks/useVerifySourceControlTokenEffect.ts

...
_Description_
_Description_
_Null_

ADM-999 [frontend][docs]: update readme and fix sonar issue

---

backend/src/main/java/heartbeat/service/pipeline/buildkite/CachePageService.java
backend/src/main/java/heartbeat/service/source/github/GitHubService.java
backend/src/test/java/heartbeat/service/pipeline/buildkite/CachePageServiceTest.java
frontend/src/containers/ConfigStep/DateRangePicker/DateRangePickerGroup.tsx
frontend/src/containers/MetricsStep/SouceControlConfiguration/SourceControlMetricSelection/index.tsx
frontend/src/context/Metrics/metricsSlice.ts
frontend/src/hooks/useVerifySourceControlTokenEffect.ts

...
_Description_
_Description_
_Null_

ADM-999 [frontend][backend]: fix bug

---

backend/src/main/java/heartbeat/service/report/calculator/ClassificationCalculator.java
backend/src/test/java/heartbeat/service/report/calculator/ClassificationCalculatorTest.java
frontend/__tests__/containers/MetricsStep/PipelineConfiguration/PipelineConfiguration.test.tsx
frontend/__tests__/containers/ReportStep/ReportStep.test.tsx
frontend/src/containers/ReportStep/BoardMetricsChart/ClassificationChart/index.tsx

...
_Description_
_Description_
_Null_

ADM-1010 [frontend][backend]: fix the bug when story point sum is zero

---

frontend/__tests__/containers/ReportStep/ReportStep.test.tsx
frontend/__tests__/utils/Util.test.tsx
frontend/src/containers/ReportStep/ReportContent/index.tsx
frontend/src/utils/util.ts

...
_Description_
_Description_
_Null_

ADM-1007 [frontend]: fix the bug ahout previous button in the report summary page

---

backend/src/main/java/heartbeat/config/CacheConfig.java
backend/src/main/resources/application.yml

...
_Description_
_Description_
_Null_

release new version 1.3.1

---

backend/src/main/java/heartbeat/config/ThreadPoolConfig.java

...
_Description_
_Description_
_Null_

fix the bug about thread pool

---

backend/src/main/java/heartbeat/config/ThreadPoolConfig.java

...
_Description_
_Description_
_Null_

[backend]: adjust the thread pool
