backend/src/models/kanban/JiraBlockReasonEnum.ts, backend/src/services/GenerateReporter/GenerateSprintReporterService.ts, backend/tests/services/GenerateKanbanReporter/GenerateSprintReporterService.test.ts
[ADM-212](https://dorametrics.atlassian.net/jira/software/projects/ADM/boards/2?selectedIssue=ADM-212)
We want to calculate percentage of different block reasons in the latest iteration
function getLatestIterationSprintName
function getAllCardsByLatestSprintName
function calculateBlockReasonPercentag
function initTotalBlockTimeForEveryReasonMap
=> ADM-212: Calculate percentage of different block reasons in the latest iteration

backend/src/services/kanban/Jira/Jira.ts, backend/src/services/kanban/Jira/JiraVerifyToken.ts, backend/tests/services/kanban/Jira/Jira.test.ts, frontend/src/app/dora/models/boardParams.ts
Use loop to send many requests, and logic and name hard to understand.
Use promise to concurrently send requests, extract and rename variables and simplify the logic.
Fix a letter case match error and logging error
=> [ADM-299] Shorten time for getting board reports

backend/src/main/resources/application-e2e.yml, backend/src/main/resources/application.yml
In order to improve the process of development and speed up development, we decide to setup the E2E environment. And E2E test will be conducted on E2E environment as below.
_Description_
1. Happy path
* E2E testing for Jira verify could be automatically be conducted against Mock server
=> ADM-380 T0A [Backend] Replace jira backend with mock sever

frontend/__tests__/src/components/Metrics/ConfigStep/PipelineTool.test.tsx, frontend/__tests__/src/components/Metrics/ConfigStep/SourceControl.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/src/constants.ts
1. change error message of SouceControl and PipelineTool components when token is invalid
2. fix unit tests
=> ADM-348 T5C - [frontend] [Config] - Source control section

backend/src/test/java/heartbeat/service/pipeline/buildkite/BuildKiteServiceTest.java
add unit test for buildkiteservice
=> ADM-408 add unit test for buildkiteservice

frontend/package.json
Set cypress timezone to prc for e2e
=> ADM-375 Set cypress timezone to prc for e2e

frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/__tests__/src/hooks/reportMapper/cycleTime.test.tsx, frontend/__tests__/src/hooks/reportMapper/deploymentFrequency.test.tsx, frontend/__tests__/src/hooks/reportMapper/leadTimeForChanges.test.tsx, frontend/__tests__/src/hooks/reportMapper/velocity.test.tsx, frontend/src/clients/report/ReportClient.ts, frontend/src/clients/report/dto/response.ts, frontend/src/components/Common/ReportForTwoColumns/index.tsx, frontend/src/components/Metrics/ReportStep/index.tsx, frontend/src/constants.ts, frontend/src/hooks/reportMapper/cycleTime.ts, frontend/src/hooks/reportMapper/deploymentFrequency.ts, frontend/src/hooks/reportMapper/leadTimeForChanges.ts, frontend/src/hooks/reportMapper/reportUIDataStructure.ts, frontend/src/hooks/reportMapper/velocity.ts, stubs/frontend/exportPage/jsons/exportData.json
Change report data type from `string` to `number`
- Frontend mockServer of report response data type
- Report page UI model data type
=> ADM-438.1 [stub][Report][frontend] Report response data mapping

frontend/__tests__/src/context/metricsSlice.test.ts, frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx, frontend/src/context/Metrics/metricsSlice.tsx
fix failed test
Test2:
Given verified Pipeline Tool
When secondly click next to go to Metrics page
Then just show Organization field selection
When filled in some pipeline settings in Deployment Frequency Settings part
And back to config page
And verified Pipeline Tool again, Then step into metrics page again
Deployment Frequency Settings part wsn't initilized
Initialize Deployment Frequency Settings part once verify Pipeline Tool
_Null_
=> [ADM-412][frontend] [Metrics] Deployment frequency settings part II

frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx, frontend/cypress/fixtures/ConfigFileForImporting.json, frontend/src/components/Metrics/ConfigStep/DateRangePicker/index.tsx, stubs/backend/jira/jira-stubs.yaml
change timestamp of endDate to 23:59:59, and save millisecond to 999
_Description_
_Description_
_Null_
=> ADM-468 [stub] [Frontend] timestamp match with mocksever

frontend/__tests__/src/context/pipelineToolSlice.test.ts, frontend/src/context/config/configSlice.ts
fix timestamp of params when get steps in metrics page
_Null_
=> ADM-468 timestamp cover mocksever

frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/SingleSelection.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx, frontend/__tests__/src/hooks/useMetricsStepValidationCheckContext.test.tsx, frontend/cypress/e2e/createANewProject.cy.ts, frontend/cypress/fixtures/ConfigFileForImporting.json, frontend/cypress/pages/metrics/metrics.ts, frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx, frontend/src/components/Metrics/MetricsStep/RealDone/index.tsx, frontend/src/components/Metrics/MetricsStepper/index.tsx, frontend/src/hooks/useMetricsStepValidationCheckContext.tsx
Only when all mandatory data in metrics page is filled, Next button is active, and users can click it to step into report page
card link: https://trello.com/c/Ko2O9LUV
Next button is always active
Next button is active only when all mandatory data in metrics page is filled
_Null_
=> ADM-450 [Metrics] Active 'Next' button in metric page

frontend/cypress/fixtures/ConfigFileForImporting.json, frontend/cypress/plugins/updateConfigJson.ts, frontend/src/context/config/configSlice.ts
fix import feature in config page: when import a json file, it failed to render data in board, pipelineTool and sourceControl
=> ADM-428 [Frontend] fix import feature in config file

frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx, frontend/src/components/Metrics/MetricsStep/index.tsx, frontend/src/components/Metrics/MetricsStepper/index.tsx
1. Remove Crew setting and Real done in metrics page for:
- LeadTime for changes
- Change failure rate
- Deployment frequency
- MTTR
2. When select Change failure rate and MTTR, it will show Deployment frequency settings component in metrics page.
**Before**
**After**
**Before**
**After**
=> ADM-466 [frontend] Remove Crew setting and Real done in metrics page

frontend/__tests__/src/context/metricsSlice.test.ts, frontend/src/components/Metrics/MetricsStep/Classification/index.tsx, frontend/src/context/Metrics/metricsSlice.tsx
fix classification settings information disappear after being back to metrics page from report page
set information in classification:
skip to next page and back:
set information in classification:
skip to next page and back:
=> ADM-455 Value in classification disappear after being back to metrics page from report page

frontend/__tests__/src/components/HomeGuide/HomeGuide.test.tsx, frontend/__tests__/src/components/Metrics/ConfigStep/ConfigStep.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStep/Classification.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStep/CycleTime.test.tsx, frontend/__tests__/src/context/configSlice.test.ts, frontend/__tests__/src/context/metricsSlice.test.ts, frontend/__tests__/src/fixtures.ts, frontend/__tests__/src/initialConfigState.ts, frontend/__tests__/src/updatedConfigState.ts, frontend/src/components/Common/ErrorNotificationAutoDismiss/index.tsx, frontend/src/components/HomeGuide/index.tsx, frontend/src/components/Metrics/ConfigStep/index.tsx, frontend/src/components/Metrics/MetricsStep/Classification/index.tsx, frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx, frontend/src/constants.ts, frontend/src/context/Metrics/metricsSlice.tsx, frontend/src/context/config/configSlice.ts
Data import validation for the cycleTime section
case1 : Compare the key value of the imported data with the name of each object in the response in the board.
（1）When different output values belong to imported data, it indicates that the current column has been deleted.
（2）When the output values before different values belong to the response, it prompts that the current column is a newly added column.
case2：Compare the value values of imported data with fixed columns.
Different values belong to imported data, indicating that the current data does not belong to a fixed column.
Data import validation for the classfication section
Display a warning message when the imported data does not match the targetFields value in the response
Data import validation for the cycleTime section
case1: …
=> ADM-452 Data import validation for the cycleTime and classification section

frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/DeploymentFrequencySettings.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStep/LeadTimeForChanges.test.tsx, frontend/__tests__/src/context/metricsSlice.test.ts, frontend/cypress/e2e/createANewProject.cy.ts, frontend/cypress/plugins/readDir.ts, frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx, frontend/src/constants.ts, frontend/src/context/Metrics/metricsSlice.tsx
when import deployment and leadTime for changes in a json file, it will verify if organization, pipelineName and step exist in buildKike response. If not, show warning message 'This organization in import data might be removed', 'This Pipeline in import data might be removed', 'Selected step of this pipeline in import data might be removed' and 'There is no step during this period for this pipeline! Please change the search time in the Config page!'.
no warning
The card is: https://trello.com/c/i1eix9d1
=> ADM-493 Verify import config file for deploymentFrequency and leadTimeForChanges[frontend][backend]

backend/src/main/java/heartbeat/client/dto/codebase/github/LeadTime.java, backend/src/main/java/heartbeat/controller/report/dto/response/LeadTimeInfo.java, backend/src/main/java/heartbeat/service/report/GenerateReporterService.java, backend/src/main/java/heartbeat/service/source/github/GitHubService.java, backend/src/test/java/heartbeat/service/pipeline/buildkite/builder/BuildKiteBuildInfoBuilder.java, backend/src/test/java/heartbeat/service/report/CalculateLeadTimeForChangesTest.java, backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java, backend/src/test/java/heartbeat/service/report/PipelineCsvFixture.java, backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java
Fix the issue that the non-PR prDelayTime is displayed as null.
When there is no PR, it should be displayed as 0:0:0
=> ADM-373 fix:[backend] fix prDelayTime is null issue

frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx, frontend/src/components/Metrics/ConfigStep/Board/index.tsx, frontend/src/components/Metrics/ConfigStep/PipelineTool/index.tsx, frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx, frontend/src/constants.ts
show warning message 'There is no step during this period for this pipeline! Please change the search time in the Config page!' when getSteps succeed but get empty array
no warning:
show warning message: 
_Null_
=> Adm 493 [frontend] add warning message when get no steps

frontend/src/components/Common/ReportForThreeColumns/index.tsx, frontend/src/constants.ts
refinement display when just one item, don't show average item
=> ADM-508 [Frontend]Remove average from export summary

frontend/src/components/Common/ReportForThreeColumns/index.tsx, frontend/src/constants.ts
refinement display when just one item, don't show average item
=> ADM-508 [Frontend]Remove average from export summary 

frontend/__tests__/src/hooks/reportMapper/leadTimeForChanges.test.tsx, frontend/src/hooks/reportMapper/leadTimeForChanges.ts
Fix issue about the displayed time. When `day` and `hours` are 0, should not show.
_Description_
_Null_
=> AdM 502 [Frontend] Lead time for change metrics display refinement

backend/src/main/java/heartbeat/client/dto/board/jira/CardHistoryResponseDTO.java, backend/src/main/java/heartbeat/client/dto/board/jira/FieldResponseDTO.java, backend/src/main/java/heartbeat/client/dto/board/jira/HistoryDetail.java, backend/src/main/java/heartbeat/client/dto/board/jira/IssueField.java, backend/src/main/java/heartbeat/client/dto/board/jira/JiraBoardConfigDTO.java, backend/src/main/java/heartbeat/client/dto/board/jira/JiraColumn.java, backend/src/main/java/heartbeat/client/dto/board/jira/JiraColumnConfig.java, backend/src/main/java/heartbeat/client/dto/board/jira/JiraColumnStatus.java, backend/src/main/java/heartbeat/client/dto/board/jira/Project.java, backend/src/main/java/heartbeat/client/dto/board/jira/Status.java, backend/src/main/java/heartbeat/client/dto/board/jira/StatusCategory.java, backend/src/main/java/heartbeat/client/dto/board/jira/StatusSelfDTO.java, backend/src/main/java/heartbeat/config/CacheConfig.java, backend/src/main/java/heartbeat/service/board/jira/JiraService.java, backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
- [Serialization of cacheable classes.](https://github.com/au-heartbeat/Heartbeat/pull/510/commits/8f94a27f789f2419da78881ebeb03b9d162f7818)
- Refactor and delete temporary cached values in JiraService.
_Description_
Here is the reason that why to Serializable the class.
The JVM is preventing Ehcache from accessing the subgraph beneath 'private final byte[] java.lang.String.value' - cache sizes may be underestimated as a result
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module \@5cc73178
_Description_
If applicable, add screenshots to help explain …
=> Adm 510 [backend] Resolve concurrency and synchronization issues in Spring backend

frontend/src/components/Metrics/ReportStep/index.tsx
…ect defalut value
In this PR, when cycle time select “ --“ as default value, we don't pass it to backend.
_Description_
_Description_
_Null_
=> ADM 497 [Frondend] Fields in Cycle time default value

backend/src/main/java/heartbeat/controller/report/dto/response/AvgMeanTimeToRecovery.java, backend/src/main/java/heartbeat/controller/report/dto/response/MeanTimeToRecovery.java, backend/src/main/java/heartbeat/controller/report/dto/response/MeanTimeToRecoveryOfPipeline.java, backend/src/main/java/heartbeat/controller/report/dto/response/ReportResponse.java, backend/src/main/java/heartbeat/controller/report/dto/response/TotalTimeAndRecoveryTimes.java, backend/src/main/java/heartbeat/service/pipeline/buildkite/BuildKiteService.java, backend/src/main/java/heartbeat/service/report/GenerateReporterService.java, backend/src/main/java/heartbeat/service/report/calculator/MeanToRecoveryCalculator.java, backend/src/main/java/heartbeat/service/report/calculator/model/FetchedData.java, backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java, backend/src/test/java/heartbeat/service/report/MeanToRecoveryCalculatorTest.java, backend/src/test/java/heartbeat/service/report/calculator/MeanToRecoveryCalculatorTest.java
- [format the recovery time to strip the trailing zeros.](https://github.com/au-heartbeat/Heartbeat/pull/516/commits/7e02cac07979ee8f3c5f9db1a114d479209ea605)
- calculate the value of mean time to recovery.
- Refactor and delete temporary cached values in GenerateReporterService.
...
_Description_
**new:** 
**old:**
_Description_
_Null_
=> Adm 445 [backend] MTTR calculation in Pipeline

frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/cypress/e2e/createANewProject.cy.ts, frontend/cypress/pages/metrics/report.ts, frontend/src/components/Metrics/ReportStep/index.tsx
=> ADM-496 [frontend] Export board CSV

frontend/__tests__/src/client/BoardClient.test.ts, frontend/__tests__/src/client/MetricsClient.test.ts, frontend/__tests__/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx, frontend/__tests__/src/context/metricsSlice.test.ts, frontend/src/clients/MetricsClient.ts, frontend/src/clients/board/BoardClient.ts, frontend/src/components/Metrics/ConfigStep/Board/index.tsx, frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx, frontend/src/context/Metrics/metricsSlice.tsx, frontend/src/hooks/useGetMetricsStepsEffect.ts, frontend/src/hooks/useVerifyBoardEffect.ts
- Handle `204` for get pipeline steps.
- Fix no done cards warning cannot reset issue. 
**Before**
1. Select a time range without a done card.
2. A warning display like `Sorry there is no card has been done, please change your collection date!` and Board Verify failed.
3. Then select a time range with done cards.
4. A warning still display, but Board verify succeed.
**After**
1. Select a time range without a done card.
2. A warning display like `Sorry there is no card has been done, please change your collection date!` and Board Verify failed.
3. Then select a time range with done cards.
4. A warning not display, and Board verify succeed.
=> ADM-471: [frontend] Error handling enhancement for frontend

frontend/__tests__/src/components/Metrics/ConfigStep/Board.test.tsx, frontend/__tests__/src/components/Metrics/ConfigStep/SourceControl.test.tsx
Build a uniform error page which includes icon, message, retry hyper link
Route to error page when it captured server errors in frontend
If error code is 5xx, it will pop out of the popup window.
If error code is 5xx, it will throw an error page.
=> ADM-519 [frontend] One uniform error handling page

frontend/__tests__/src/components/Metrics/MetricsStep/CycleTime.test.tsx, frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx, frontend/src/components/Metrics/MetricsStep/CycleTime/style.tsx, frontend/src/components/Metrics/MetricsStep/index.tsx
- Remove limitation of supporting one column marked as done.
| Before | After | 
|--------|--------|
| <img width="1220" alt="Screenshot 2023-08-03 at 13 49 25" src="https://github.com/au-heartbeat/Heartbeat/assets/112382375/73f3f64c-5331-43aa-beb7-977fd4d8daff"> | <img width="1161" alt="Screenshot 2023-08-03 at 13 52 54" src="https://github.com/au-heartbeat/Heartbeat/assets/112382375/b7336237-773f-499a-95be-47fd7728201f"> | 
| <img width="337" alt="Screenshot 2023-08-03 at 13 51 23" src="https://github.com/au-heartbeat/Heartbeat/assets/112382375/66256899-7be9-411b-a5de-47ed26379932"> | <img width="294" alt="Screenshot 2023-08-03 at 13 54 07" src="https://github.com/au-heartbeat/Heartbeat/assets/112382375/d2d659f9-7797-4817-a513-91b7d6e77574"> |
=> ADM-537:[frontend] Support multiple Done columns

frontend/__tests__/src/components/Metrics/ConfigStep/Board.test.tsx, frontend/__tests__/src/components/Metrics/ConfigStep/NoCardPop.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/src/components/Metrics/ConfigStep/Board/index.tsx, frontend/src/components/Metrics/ConfigStep/NoDoneCardPop/index.tsx
- Modify error message when no card.
Board verify only return done cards.
Crews setting only consider the users who has been assigned to the done cards.
When this is no done card, it will show error message.
Board verify only return done cards.
Crews setting include the all users who has been assigned to one card.
When this is no card, it will show error message.
=> ADM-537:[frontend] Modify error message when no card.

backend/src/main/java/heartbeat/client/JiraFeignClient.java, backend/src/main/java/heartbeat/service/board/jira/JiraService.java, backend/src/main/java/heartbeat/service/report/GenerateReporterService.java, backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java, backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java
Summary
When export board CSV, only calculate cycle time for dong cards.
Before
After
=> ADM-540: [backend]Cycle time for undone cards

frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx
Only when the Cycle time component marks one column as done, the Real down component will be reset.
Whenever the Cycle time component updates, the Real down component resets.
_Description_
Only when the Cycle time component marks one column as done, the Real down component will be reset.
Options change to Done, will reset:
Done change to other options, will reset:
Options except Done change to other options, will not reset:
_Null_
=> ADM-550 [Fox][frontend] - Real down reset issue

frontend/__tests__/src/components/Metrics/ConfigStep/DateRangePicker.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx, frontend/src/components/Metrics/ConfigStep/DateRangePicker/index.tsx
Justify the time interval automatically generated on the config page and its related tests.
=> ADM 551: [frontend] Adjust AUTO To date when user select From date

frontend/__tests__/src/components/Metrics/ConfigStep/ConfigStep.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStep/MetricsStep.test.tsx, frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx, frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx, frontend/src/components/Metrics/ConfigStep/index.tsx, frontend/src/components/Metrics/MetricsStep/index.tsx, frontend/src/components/Metrics/MetricsStepper/index.tsx, frontend/src/components/Metrics/ReportStep/index.tsx
Use lazy load to improve the performance of Metrics module.
There are 90 requests when we import config.
There are 45 requests when we import config.
=> ADm-546: [frontend] Performance optimization

frontend/src/components/Metrics/MetricsStepper/index.tsx
The 'Next' button should be disabled.
_Description_
_Description_
_Null_
=> ADM-566:[frontend] fix the next button can not be disabled bug

frontend/__tests__/src/components/DateDisplay/CollectionDuration.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/src/clients/report/CSVClient.ts, frontend/src/clients/report/dto/request.ts, frontend/src/components/Common/CollectionDuration/index.tsx, frontend/src/components/Common/CollectionDuration/style.tsx, frontend/src/components/Metrics/MetricsStep/index.tsx, frontend/src/components/Metrics/ReportStep/index.tsx, frontend/src/theme.ts
- Add the collection duration display in both `metrics` and `report` page.
- Add the collection duration info in the exported csv file name.
_Null_
=> ADM-589 Add time duration display in UI and csv file name

backend/src/main/java/heartbeat/controller/source/dto/SourceControlDTO.java, backend/src/test/java/heartbeat/controller/source/GithubControllerTest.java, frontend/__tests__/src/components/Metrics/MetricsStepper/MetricsStepper.test.tsx, frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx, frontend/__tests__/src/utils/Util.test.tsx, frontend/src/components/Metrics/ReportStep/index.tsx, frontend/src/utils/util.ts
Make the jira board token to be an empty string when use don't need the jira board information
=> ADM-611:[frontend]feat: clean encoded jira token for empty token

backend/src/main/java/heartbeat/service/report/calculator/CycleTimeCalculator.java, backend/src/test/java/heartbeat/service/report/CycleTimeCalculatorTest.java, backend/src/test/java/heartbeat/service/report/CycleTimeFixture.java
… get correct cycleTime
To support column multi-status to get correct cycleTime, we don't need to change the function code. So I just add 2 tests to cover the business scenarios.
1. should sum all the statuses when a state have multiple statues
For example: The Doing state has 2 statues.
> In Doing -> Doing
> Doing -> Doing
2. should sum all the statues when multiple swimlane mapping to the same metric
For example: The **In Dev** has 2 swimlanes.
> Doing -> In Dev
> Testing -> In Dev
_Null_
=> ADM-645:[backend]test: add test for supporting column multi-status to get correct cycleTime

frontend/__tests__/src/client/ReportClient.test.ts, frontend/__tests__/src/components/Metrics/ReportStep/ReportStep.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/__tests__/src/hooks/useGenerateReportEffect.test.tsx, frontend/src/clients/report/ReportClient.ts, frontend/src/clients/report/dto/response.ts, frontend/src/components/Loading/index.tsx, frontend/src/components/Loading/style.tsx, frontend/src/components/Metrics/ReportStep/index.tsx, frontend/src/constants.ts, frontend/src/hooks/reportMapper/report.ts, frontend/src/hooks/useGenerateReportEffect.ts
[Frontend] Keep polling from generate report callback to fetch the result
_Description_
_Description_
_Null_
=> Adm 640: [Frontend] Keep polling from generate report callback to fetch the result

frontend/src/components/Metrics/MetricsStep/CycleTime/index.tsx, frontend/src/components/Metrics/MetricsStep/CycleTime/style.tsx
enhance style for tooltip
_Description_
_Description_
before:
after:
_Null_
=> [frontend] ADM-646: enhance style for tooltip

backend/src/main/java/heartbeat/exception/GithubRepoEmptyException.java, backend/src/main/java/heartbeat/exception/RestResponseEntityExceptionHandler.java, backend/src/main/java/heartbeat/service/source/github/GitHubService.java, backend/src/test/java/heartbeat/exception/RestResponseEntityExceptionHandlerTest.java, backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java, frontend/src/components/Metrics/ConfigStep/SourceControl/index.tsx
fronted:
When the Source Control input receives Github tokens and is verified, the button should update to 'Verify' instead of 'Reset'. This logic is synchronized with the Board and Pipeline Tool.
backend:
After inputting Github tokens, if the server verifies the token and returns an empty Github repositories result, then an exception should be thrown.
_Description_
_Description_
_Null_
=> Adm-649:[Backend][Frontend] Verify failed when return GitHub repos size empty

docs/src/i18n/en/nav.ts
Reverts au-heartbeat/Heartbeat#796
=> Revert "[docs]: fix key and slug"

ops/infra/nginx.conf
...
_Description_
_Description_
_Null_
=> ADM-620:[frontend]fix: fix regular to swagger in middle

docs/src/content/docs/en/spikes/tech-spikes-split-verify-of-buildkite.mdx, docs/src/i18n/en/nav.ts
add docs for spike BuildKite token and get Info
_Description_
_Description_
_Null_
=> ADM-678:[docs]feat: add docs for spike BuildKite

backend/src/test/java/heartbeat/service/report/WorkDayTest.java, frontend/cypress/e2e/createANewProject.cy.ts, frontend/src/components/Common/ReportGrid/ReportCardItem/index.tsx, frontend/src/components/Common/ReportGrid/ReportCardItem/style.tsx
fix tooltip style
_Description_
_Description_
_Null_
=> [frontend]Adm 688 tooltip fix

backend/README.md, backend/src/main/java/heartbeat/service/board/jira/JiraService.java, backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java
Some requests running in threads might be blocked when thread pool core size is not enough although it did not reach to the max size. Then refined it as removing some uncontrolled executors. 
Some requests running in threads might be blocked
No requests running in threads might be blocked
For multiple thread calling, we can not run it anywhere. We should fine that the exact thing we have to use multiple threads essentially.
=> ADM-674:[backend] Remove uncontrolled executor and refine testing.

backend/src/test/java/heartbeat/controller/report/GenerateReporterControllerTest.java
...
shouldReturnCallBackUrlWithAcceptedStatusAndInvokeGenerateBoardReportWhenReportTypeIsBoard because async method call.
Add thread.sleep(2000) to make sure async method call don't affect test method.
_Null_
=> ADM-727:[backend]feat: fix failed tst

frontend/__tests__/src/containers/ReportStep/ReportStep.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/src/containers/MetricsStep/style.tsx, frontend/src/containers/ReportStep/ReportDetail/board.tsx, frontend/src/containers/ReportStep/index.tsx
generate detail report relate to 'classification'
_Description_
_Description_
_Null_
=> [frontend] ADM-728: generate detail report relate to 'classification'

frontend/__tests__/src/components/Common/ReportForThreeColumns.test.tsx, frontend/__tests__/src/components/Loading/Loading.test.tsx, frontend/__tests__/src/containers/ReportStep/BoardMetrics.test.tsx, frontend/__tests__/src/containers/ReportStep/ReportDetail/board.test.tsx, frontend/src/components/Common/ReportForThreeColumns/index.tsx, frontend/src/components/Loading/index.tsx, frontend/src/components/Loading/style.tsx, frontend/src/containers/ReportStep/BoradMetrics/index.tsx, frontend/src/containers/ReportStep/BoradMetrics/style.tsx, frontend/src/containers/ReportStep/ReportDetail/board.tsx
add loading for table and report title
_Description_
_Description_
_Null_
=> [frontend]ADM-728: add loading for table and report title

frontend/__tests__/src/components/Common/ReportForThreeColumns.test.tsx, frontend/__tests__/src/components/Loading/Loading.test.tsx, frontend/__tests__/src/containers/ReportStep/ReportDetail/board.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/src/components/Loading/index.tsx, frontend/src/containers/ReportStep/BoradMetrics/index.tsx
1. extra const for loading
2. placement type use left replace start
_Description_
_Description_
_Null_
=> [frontend]ADM-728: extra const and change type for placement

frontend/__tests__/src/client/BoardClient.test.ts, frontend/__tests__/src/client/PipelineToolClient.test.ts, frontend/__tests__/src/containers/MetricsStep/DeploymentFrequencySettings/PresentationForErrorCases.test.tsx, frontend/__tests__/src/fixtures.ts, frontend/src/clients/Httpclient.ts, frontend/src/clients/pipeline/PipelineToolClient.ts, frontend/src/components/Metrics/MetricsStep/DeploymentFrequencySettings/PresentationForErrorCases/index.tsx, frontend/src/constants/resources.ts, frontend/src/exceptions/ExceptionType.ts, frontend/src/exceptions/TimeoutException.ts
1. 根据业务需求，我们将axios所体现的`超时`和`网络问题`都视为可以重试的情形，并提供了相应的UI；所以在基类HttpClient上对这些特殊的错误code做了处理，以便业务型的client总能拿到标准的输出。
2. 5系列的错误应直接将用户redirect到`/error-page`路由展示相应页面；目前做了一个比较粗糙的处理，如果希望利用router状态进行跳转（避免整个页面的重新加载，包括脚本，文档，css等），需要将router集成到store里，effort较大，需要新开一张卡track。
_Description_
_Description_
_Null_
=> ADM-714: [frontend] handle 5 series error routing

frontend/__tests__/components/Common/NotificationButton/NotificationButton.test.tsx, frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx, frontend/__tests__/containers/ReportButtonGroup.test.tsx, frontend/__tests__/containers/ReportStep/ReportStep.test.tsx, frontend/__tests__/hooks/useExportCsvEffect.test.tsx, frontend/__tests__/hooks/useGenerateReportEffect.test.tsx, frontend/__tests__/hooks/useNotificationLayoutEffect.test.tsx, frontend/cypress/e2e/createANewProject.cy.ts, frontend/src/components/Common/NotificationButton/index.tsx, frontend/src/components/Common/NotificationButton/style.tsx, frontend/src/constants/resources.ts, frontend/src/containers/ConfigStep/index.tsx, frontend/src/containers/MetricsStep/index.tsx, frontend/src/containers/ReportButtonGroup/index.tsx, frontend/src/containers/ReportStep/BoardMetrics/index.tsx, frontend/src/containers/ReportStep/DoraMetrics/index.tsx, frontend/src/containers/ReportStep/index.tsx, frontend/src/containers/ReportStep/style.tsx, frontend/src/hooks/useExportCsvEffect.ts, frontend/src/hooks/useGenerateReportEffect.ts, frontend/src/hooks/useNotificationLayoutEffect.ts
...
_Description_
_Description_
_Null_
=> ADM-747: [frontend] feat: handle error

frontend/__tests__/containers/MetricsStep/CycleTime.test.tsx, frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx, frontend/src/containers/MetricsStep/CycleTime/Table/index.tsx, frontend/src/containers/MetricsStep/index.tsx, frontend/src/containers/MetricsStepper/index.tsx
Reference: https://dorametrics.atlassian.net/browse/ADM-740
1. show not show real done when cycle time by status
2. update: By Board Column mapping -> By Colum, By Board Status mapping -> By Status
=> [ADM-740] show not show real done when cycle time by status

frontend/src/containers/ReportStep/DoraMetrics/index.tsx
前端错误处理重构以后，断网的情况会触发超时的 Error，对这种情况在 Dashboard 也展示 Retry 按钮
_Description_
_Description_
_Null_
=> ADM-fix: [frontend] fix: fix retry

frontend/__tests__/containers/MetricsStep/CycleTime.test.tsx, frontend/src/containers/MetricsStep/CycleTime/Table/index.tsx
In cycle time setting table, the letters in board column are not capitalized which is not matched the Jira board column, so we need to fix it. [JIRA](https://dorametrics.atlassian.net/browse/ADM-734?atlOrigin=eyJpIjoiNDk1MWNiOWZhZDFmNGNjMzgyNTBkNjVkNWE5M2I0NDEiLCJwIjoiaiJ9)
...
The letters in board column are not capitalized.
The letters in board column are capitalized.
_Null_
=> ADM-734: [frontend] fix: set letters in board column to uppercase

backend/src/main/java/heartbeat/service/report/calculator/ChangeFailureRateCalculator.java, backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java, backend/src/test/java/heartbeat/service/report/calculator/CalculateChangeFailureRateTest.java, backend/src/test/java/heartbeat/service/report/calculator/CalculateDeploymentFrequencyTest.java, backend/src/test/java/heartbeat/service/source/github/GithubServiceTest.java, frontend/cypress/e2e/createANewProject.cy.ts
After discussion, we have decided to modify the formula of ChangeFailureRate. The formula now excludes passed builds that haven't reached the final step.
The formula includes passed builds that haven't reached the final step.
The formula now excludes passed builds that haven't reached the final step.
_Null_
=> [ADM-766][Backend] fix formula of ChangeFailureRate

backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java, backend/src/test/java/heartbeat/service/report/KanbanFixture.java, backend/src/test/java/heartbeat/service/report/KanbanServiceTest.java, backend/src/test/java/heartbeat/service/report/PipelineServiceTest.java, backend/src/test/java/heartbeat/service/report/ReportServiceTest.java
add test content
The test coverage is incomplete
add test content
_Null_
=> ADM-794:[backend]fix: add test for pipeline

frontend/src/context/Metrics/metricsSlice.ts
...
_Description_
_Description_
_Null_
=> ADM-762: [frontend] refactor: make code easier to understand

ops/infra/nginx.conf
... Our report page numbers are not displaying in Roboto font. We need to fix the issue with Roboto font not displaying.
_Description_
_Null_
=> ADM-800:[frontend][backend]fix: fix the issue of Roboto font not displaying

backend/src/main/java/heartbeat/controller/report/ReportController.java, backend/src/main/java/heartbeat/controller/report/dto/request/GenerateReportRequest.java, backend/src/main/java/heartbeat/controller/report/dto/response/MetricsDataCompleted.java, backend/src/main/java/heartbeat/controller/report/dto/response/ReportResponse.java, backend/src/main/java/heartbeat/handler/AsyncMetricsDataHandler.java, backend/src/main/java/heartbeat/handler/base/AsyncDataBaseHandler.java, backend/src/main/java/heartbeat/service/report/GenerateReporterService.java, backend/src/main/java/heartbeat/service/report/MetricsDataDTO.java, backend/src/main/java/heartbeat/service/report/ReportService.java, backend/src/test/java/heartbeat/controller/report/ReporterControllerTest.java, backend/src/test/java/heartbeat/controller/report/reportResponse.json, backend/src/test/java/heartbeat/handler/AsyncMetricsDataHandlerTest.java, backend/src/test/java/heartbeat/service/report/GenerateReporterServiceTest.java, backend/src/test/java/heartbeat/service/report/ReportServiceTest.java, docs/src/content/docs/en/designs/refinement-on-generate-report.mdx
1.click ‘next’  to the report page
2.click ‘export  pipeline data’ button
3.failed to export file and show 
After some research we found out the root cause of this kind of issue is that our backend doesn't keep the atomicity consistency. So I refactor our code and change the design of status life cycle.
When we click `export pipeline data`, sometimes we will encounter error and direct us to error page.
As long as the button is clickable, clicking it will export regarding file.
_Null_
=> ADM-791:[backend][docs]: Fix the atomicity issue, add more tests and update docs

frontend/__tests__/containers/ConfigStep/Board.test.tsx, frontend/__tests__/containers/ConfigStep/PipelineTool.test.tsx, frontend/__tests__/containers/ConfigStep/SourceControl.test.tsx, frontend/__tests__/hooks/useVerifyBoardEffect.test.tsx, frontend/__tests__/hooks/useVerifyPipelineToolEffect.test.tsx, frontend/__tests__/hooks/useVerifySourceControlTokenEffect.test.tsx, frontend/cypress/e2e/createANewProject.cy.ts, frontend/cypress/e2e/importAProject.cy.ts, frontend/cypress/fixtures/NewConfigFileForImporting.json, frontend/cypress/fixtures/OldConfigFileForImporting.json, frontend/cypress/fixtures/fixtures.ts, frontend/src/constants/commons.ts, frontend/src/containers/ConfigStep/Board/index.tsx, frontend/src/containers/ConfigStep/PipelineTool/index.tsx, frontend/src/containers/ConfigStep/SourceControl/index.tsx, frontend/src/hooks/useVerifyBoardEffect.ts, frontend/src/hooks/useVerifyPipelineToolEffect.ts, frontend/src/hooks/useVerifySourceControlTokenEffect.ts
Reference: https://dorametrics.atlassian.net/browse/ADM-783
1. refactor config for board/pipeline/source 
2. fix board/pipeline/source input change strategy
3. update validation strategy
https://github.com/au-heartbeat/Heartbeat/assets/17806850/c33a2f99-7cda-4c0f-8c5a-af93cd12a825
board/pipeline/source control of config page will keep user's input
=> [ADM-783][Frontend] Keep user's input for board/pipeline/source control of config page

.buildkite/pipeline.yml
Currently we use Playwright to run E2E instead of Cypress.
- fix buildkite yml
=> ADM-785:[E2E] fix buildkite yml

frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx, frontend/src/components/Common/EmptyContent/styles.tsx, frontend/src/containers/MetricsStep/index.tsx, frontend/src/containers/MetricsStep/style.tsx
...
1.not show board config title in metics page
2. wrong button text 'retry'
3. wrong styles about retry message 
1. show board config title when board config context is empty
2. replace 'retry' button text to 'try again'
3. fix the font-size ,  image size for retry content
_Null_
=> [Frontend] Fix/adm 718 fix style issues for desk check

backend/src/main/java/heartbeat/controller/board/dto/request/StoryPointsAndCycleTimeRequest.java, backend/src/main/java/heartbeat/controller/report/dto/request/JiraBoardSetting.java, backend/src/main/java/heartbeat/service/board/jira/JiraService.java, backend/src/main/java/heartbeat/service/report/KanbanService.java, backend/src/test/java/heartbeat/service/jira/JiraBoardConfigDTOFixture.java, backend/src/test/java/heartbeat/service/jira/JiraServiceTest.java, frontend/__tests__/containers/MetricsStep/Advance.test.tsx, frontend/__tests__/containers/MetricsStepper/MetricsStepper.test.tsx, frontend/__tests__/context/metricsSlice.test.ts, frontend/__tests__/fixtures.ts, frontend/src/clients/report/dto/request.ts, frontend/src/constants/resources.ts, frontend/src/containers/MetricsStep/Advance/Advance.tsx, frontend/src/containers/MetricsStep/Advance/style.tsx, frontend/src/containers/MetricsStep/index.tsx, frontend/src/containers/MetricsStepper/index.tsx, frontend/src/containers/ReportStep/BoardMetrics/index.tsx, frontend/src/context/Metrics/metricsSlice.ts
Due to board token permissions, data for 'story point' and 'block' cannot be fetched from the target field returned by the Jira API call using their token (in the covertCustomFieldKey method). Hence, the key for the corresponding custom field for story points is allowed to be set via environment variables beforehand, and the key record of the respective custom field will then be found in the return value of get real done.
Could not set `Advance` field.
Could set `Advance` field.
_Null_
=> ADM-813[frontend/backend]: add Advance field in metrics page

frontend/__tests__/containers/MetricsStep/Crews.test.tsx, frontend/__tests__/containers/MetricsStep/CycleTime.test.tsx, frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/DeploymentFrequencySettings.test.tsx, frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection.test.tsx, frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx, frontend/__tests__/context/metricsSlice.test.ts, frontend/src/containers/ConfigStep/Board/index.tsx, frontend/src/containers/ConfigStep/PipelineTool/index.tsx, frontend/src/containers/MetricsStep/Classification/index.tsx, frontend/src/containers/MetricsStep/Crews/AssigneeFilter.tsx, frontend/src/containers/MetricsStep/Crews/index.tsx, frontend/src/containers/MetricsStep/CycleTime/FlagCard.tsx, frontend/src/containers/MetricsStep/CycleTime/Table/index.tsx, frontend/src/containers/MetricsStep/DeploymentFrequencySettings/PipelineMetricSelection/index.tsx, frontend/src/containers/MetricsStep/RealDone/index.tsx, frontend/src/containers/MetricsStep/index.tsx, frontend/src/context/Metrics/metricsSlice.ts
...
call get board Info and pipeline info every time when enter metrics page
only call get board info and pipeline info when trigger verify call
=> ADM-812: [frontend]: only call get board info and pipeline info when user trigger verify

frontend/__tests__/components/Common/ReportForThreeColumns.test.tsx, frontend/src/components/Common/ReportForThreeColumns/index.tsx
set default value for valueList when is empty
_Description_
_Description_
_Null_
=> [frontend]ADM-755: set default value for valueList when is empty

frontend/__tests__/containers/MetricsStep/MetricsStep.test.tsx
...
_Description_
_Description_
_Null_
=> ADM-831:[frontend]feat: add pipeline is future time check

frontend/__tests__/containers/MetricsStep/DeploymentFrequencySettings/SingleSelection.test.tsx, frontend/__tests__/utils/Util.test.tsx, frontend/src/containers/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx, frontend/src/utils/util.ts
pipeline name can not be repeatable selection
_Description_
_Description_
_Null_
=> [frontend]ADM-767: make disable for pipeline name

backend/src/main/java/heartbeat/service/report/WorkDay.java, backend/src/test/java/heartbeat/TestFixtures.java
...
_Description_
_Description_
_Null_
=> fix(sonar): fix sonar issues

frontend/src/containers/MetricsStep/DeploymentFrequencySettings/SingleSelection/index.tsx
sort the disabled options
_Description_
_Description_
_Null_
=> [frontend] ADM-767: sort the disabled options

frontend/e2e/fixtures/index.ts, frontend/e2e/pages/metrics/ReportStep.ts, frontend/playwright.config.ts
Since our local api take longer than CI env, entends the local TIMEOUT.
_Description_
_Description_
_Null_
=> chore: extend the timeout of e2e local assertion because of the poor condition of local env.

backend/src/main/java/heartbeat/service/board/jira/JiraService.java, backend/src/main/java/heartbeat/service/pipeline/buildkite/CachePageService.java, backend/src/main/java/heartbeat/service/report/CSVFileGenerator.java, backend/src/main/java/heartbeat/service/report/KanbanCsvService.java, backend/src/main/java/heartbeat/service/report/calculator/ClassificationCalculator.java, backend/src/test/java/heartbeat/service/pipeline/buildkite/CachePageServiceTest.java
...
_Description_
_Description_
_Null_
=> Adm 851[Backend] fix Snoar refactor issues

frontend/src/containers/MetricsStep/ReworkSettings/ReworkDialog/index.tsx, frontend/src/containers/MetricsStep/ReworkSettings/ReworkDialog/style.tsx
enhance style for img and note text
_Description_
_Description_
_Null_
=> [ADM-774] style: enhance style for img and note text

docs/src/content/docs/en/spikes/tech-spikes-chart-api-solutions.mdx
...
_Description_
_Description_
_Null_
=> ADM-886:[docs]docs: update chart API docs content

frontend/src/containers/ConfigStep/DateRangePicker/DateRangePicker.tsx, frontend/src/containers/ConfigStep/DateRangePicker/validation.ts
When select `startDate` or `endDate`, it is no longer limited by its corresponding `endDate` or `startDate`.
_Description_
_Description_
_Null_
=> [ADM-877][frontend]: feat: remove the limit of start-date & end-date selection.

frontend/__tests__/containers/ConfigStep/MetricsTypeCheckbox.test.tsx, frontend/__tests__/containers/ConfigStep/PipelineTool.test.tsx, frontend/__tests__/containers/MetricsStepper/MetricsStepper.test.tsx, frontend/__tests__/fixtures.ts, frontend/__tests__/utils/Util.test.tsx, frontend/src/constants/resources.ts, frontend/src/containers/ConfigStep/PipelineTool/index.tsx, frontend/src/containers/MetricsStepper/index.tsx
Do not clear the configuration settings when returning from the metric page to the configuration page.
...
Auto clear board, pipeline and source control config when back to config page from metric page
1. do not auto clear config 
2. remove pipeline tools type GoCD
3. refactor unit test style
4. remove unit tests that are no longer needed.
=> [frontend] feat/adm 811: Do not clear the configuration settings when returning from the metric page to the configuration page.

frontend/__tests__/components/Common/DateRangeViewer/DateRangeViewer.test.tsx, frontend/__tests__/containers/ReportStep/ReportStep.test.tsx, frontend/src/clients/board/dto/request.ts, frontend/src/components/Common/DateRangeViewer/index.tsx, frontend/src/containers/ConfigStep/DateRangePicker/validation.ts, frontend/src/context/config/configSlice.ts, frontend/src/utils/util.ts
...
_Description_
_Description_
_Null_
=> ADM-878:[frontend]refactor: rename date range

frontend/src/containers/ConfigStep/DateRangePicker/DateRangePicker.tsx, frontend/src/containers/ConfigStep/DateRangePicker/DateRangePickerGroup.tsx, frontend/src/containers/ConfigStep/DateRangePicker/types.ts
...
_Description_
_Description_
_Null_
=> [ADM-931][frontend] feat: fix sorting clickable when any time range is invalid

frontend/__tests__/components/Common/DateRangeViewer/DateRangeViewer.test.tsx, frontend/__tests__/context/stepperSlice.test.ts, frontend/src/components/Common/DateRangeViewer/index.tsx, frontend/src/components/Common/DateRangeViewer/style.tsx, frontend/src/containers/ReportStep/index.tsx, frontend/src/context/stepper/StepperSlice.tsx, frontend/src/hooks/useGenerateReportEffect.ts, frontend/src/hooks/useGetBoardInfo.ts, frontend/src/hooks/useGetMetricsStepsEffect.ts, frontend/src/hooks/useGetPipelineToolInfoEffect.ts
ADM-928 [frontend]: fix dc issues and implement the retry function
_Description_
_Description_
_Null_
=> ADM-928 [frontend]: fix dc issues and implement the retry function

frontend/__tests__/containers/ReportStep/ChartAndTitleWrapper.test.tsx, frontend/__tests__/containers/ReportStep/style.test.tsx, frontend/e2e/fixtures/import-file/chart-result.ts, frontend/src/containers/ReportStep/ChartAndTitleWrapper/index.tsx, frontend/src/containers/ReportStep/ChartAndTitleWrapper/style.tsx, frontend/src/theme.ts, ops/check.sh
1. change thumbup icon position
2. change trend number color
_Description_
_Description_
_Null_
=> Adm 944 [frontend] change thumbup icon position

frontend/__tests__/components/Common/DateRangeViewer/DateRangeViewer.test.tsx, frontend/__tests__/context/stepperSlice.test.ts, frontend/src/components/Common/DateRangeViewer/index.tsx, frontend/src/context/stepper/StepperSlice.tsx, frontend/src/hooks/useGenerateReportEffect.ts, frontend/src/hooks/useGetBoardInfo.ts, frontend/src/hooks/useGetMetricsStepsEffect.ts, frontend/src/hooks/useGetPipelineToolInfoEffect.ts
1. change data structure: loading status instead of error
2. use isLoading is true to represent loading status
3. use isLoaded and isLoadedWithError to represent loading error
...
_Description_
_Description_
_Null_
=> ADM-955: [frontend] change page loading status representation

frontend/__tests__/containers/ReportStep/ReportStep.test.tsx, frontend/__tests__/fixtures.ts, frontend/__tests__/hooks/reportMapper/changeFailureRate.test.tsx, frontend/__tests__/hooks/reportMapper/deploymentFrequency.test.tsx, frontend/__tests__/hooks/reportMapper/meanTimeToRecovery.test.tsx, frontend/__tests__/hooks/reportMapper/report.test.tsx, frontend/src/containers/ReportStep/DoraMetricsChart/ChartOption.ts, frontend/src/containers/ReportStep/DoraMetricsChart/index.tsx, frontend/src/hooks/reportMapper/deploymentFrequency.ts, frontend/src/hooks/reportMapper/devChangeFailureRate.ts, frontend/src/hooks/reportMapper/devMeanTimeToRecovery.ts, frontend/src/utils/util.ts
fix the bug when selecting multiple pipeline the doar chart show error.
such as `pr lead time`
In the list, the average is the below picture:
but the chart is the below picture:
In the list, the average is the below picture:
the chart is the below picture:
_Null_
=> ADM-963 [frontend]: fix bug of multiple pipeline

frontend/src/containers/ReportStep/BoardMetricsChart/index.tsx, frontend/src/containers/ReportStep/ChartAndTitleWrapper/index.tsx
fix the rework loading bug, and hide the trend icon when data don't load completely.
_Null_
=> ADM-960 [frontend]: fix the rework loading bug

frontend/README.md
...
_Description_
_Description_
_Null_
=> Adm-935 [frontend] change readme

README.md, frontend/__tests__/constants/fileConfig/fileConfig.test.ts, frontend/__tests__/fixtures.ts, frontend/e2e/fixtures/create-new/metrics-step.ts, frontend/e2e/fixtures/cycle-time-by-status/cycle-time-by-column-fixture.ts, frontend/e2e/fixtures/cycle-time-by-status/cycle-time-by-status-fixture.ts, frontend/e2e/fixtures/import-file/calculate-with-holiday-config-file.ts, frontend/e2e/fixtures/import-file/multiple-done-config-file.ts, frontend/e2e/fixtures/import-file/partial-metrics-show-chart.ts, frontend/e2e/fixtures/import-file/partial-time-ranges-success.ts, frontend/e2e/fixtures/import-file/unhappy-path-file.ts, frontend/e2e/fixtures/input-files/add-flag-as-block-config-file.template.json, frontend/e2e/fixtures/input-files/calculate-with-holiday-config-file.template.json, frontend/e2e/fixtures/input-files/charting-unhappy-path-config-file.template.json, frontend/e2e/fixtures/input-files/cycle-time-by-status-config-file.template.json, frontend/e2e/fixtures/input-files/hb-e2e-for-importing-file.template.json, frontend/e2e/fixtures/input-files/multiple-done-config-file.template.json, frontend/e2e/fixtures/input-files/partial-metrics-show-chart.template.json, frontend/e2e/fixtures/input-files/partial-time-ranges-success.template.json, frontend/e2e/fixtures/input-files/pipeline-no-org-config-file.template.json, frontend/e2e/fixtures/input-files/unhappy-path-config-file.template.json, frontend/e2e/pages/metrics/config-step.ts, frontend/src/constants/fileConfig.ts, frontend/src/constants/resources.ts, frontend/src/containers/ConfigStep/BasicInfo/index.tsx
...
_Description_
_Description_
_Null_
=> ADM-952 [frontend] change to lower case

frontend/__tests__/hooks/useGenerateReportEffect.test.tsx, frontend/__tests__/utils/Util.test.tsx, frontend/src/clients/report/CSVClient.ts, frontend/src/containers/ReportStep/ReportContent/index.tsx, frontend/src/containers/ReportStep/index.tsx, frontend/src/containers/ShareReport/index.tsx, frontend/src/hooks/useGenerateReportEffect.ts, frontend/src/layouts/ShareReportTrigger/index.tsx, frontend/src/layouts/ShareReportTrigger/style.tsx, frontend/src/utils/util.ts
...
_Description_
_Description_
_Null_
=> ADM-973 [frontend] retry all when retry

frontend/__tests__/containers/ReportStep/ReportDetail/board.test.tsx, frontend/__tests__/containers/ReportStep/ReportDetail/dora.test.tsx, frontend/__tests__/containers/ReportStep/ReportDetail/withBack.test.tsx, frontend/src/containers/ReportStep/ReportContent/index.tsx, frontend/src/containers/ReportStep/ReportDetail/board.tsx, frontend/src/containers/ReportStep/ReportDetail/dora.tsx, frontend/src/containers/ReportStep/ReportDetail/style.tsx, frontend/src/containers/ReportStep/ReportDetail/withBack.tsx, frontend/src/containers/ReportStep/index.tsx, frontend/src/containers/ShareReport/index.tsx, frontend/src/context/config/configSlice.ts
...
_Description_
_Description_
_Null_
=> ADM-986 [frontend]: fix the bug that in the board details in the share page we don't find the classification data

frontend/__tests__/containers/ReportStep/DoraMetrics.test.tsx, frontend/e2e/pages/metrics/config-step.ts, frontend/src/components/Common/NewFunctionsLabel/style.tsx, frontend/src/components/Common/ReportGrid/ReportCard/index.tsx, frontend/src/containers/ConfigStep/ResetConfirmDialog/index.tsx, frontend/src/containers/ConfigStep/ResetConfirmDialog/style.tsx, frontend/src/containers/MetricsStepper/ConfirmDialog/index.tsx, frontend/src/containers/MetricsStepper/ConfirmDialog/style.tsx, frontend/src/containers/ReportStep/ChartAndTitleWrapper/index.tsx, frontend/src/containers/ReportStep/ChartAndTitleWrapper/style.tsx
...
_Description_
_Description_
_Null_
=> ADM-997 [frontend]: fix dc issues

docs/src/content/docs/en/spikes/tech-spikes-github-api-for-pull-request-info-by-token.mdx
...
_Description_
_Description_
_Null_
=> ADM-1001 [docs]: fix the dc issues

frontend/__tests__/context/metricsSlice.test.ts, frontend/e2e/pages/metrics/metrics-step.ts, frontend/src/containers/MetricsStep/SouceControlConfiguration/index.tsx, frontend/src/context/Metrics/metricsSlice.ts, frontend/src/context/config/configSlice.ts, frontend/src/hooks/useGetSourceControlConfigurationBranchEffect.tsx, frontend/src/hooks/useGetSourceControlConfigurationOrganizationEffect.tsx, frontend/src/hooks/useGetSourceControlConfigurationRepoEffect.tsx
...
_Description_
_Description_
_Null_
=> ADM-999 [frontend][backend]: fix e2e test and change the logic

backend/src/main/java/heartbeat/service/pipeline/buildkite/CachePageService.java, backend/src/test/java/heartbeat/service/pipeline/buildkite/CachePageServiceTest.java, frontend/__tests__/containers/MetricsStep/SourceControlConfiguration/SourceControlConfiguration.test.tsx, frontend/__tests__/containers/MetricsStep/SourceControlConfiguration/SourceControlMetricSelection.test.tsx, frontend/__tests__/hooks/useGetSourceControlConfigurationBranchEffect.test.tsx, frontend/__tests__/hooks/useGetSourceControlConfigurationCrewEffect.test.tsx, frontend/__tests__/hooks/useGetSourceControlConfigurationRepoEffect.test.tsx, frontend/src/constants/resources.ts, frontend/src/containers/MetricsStep/SouceControlConfiguration/SourceControlMetricSelection/index.tsx, frontend/src/containers/MetricsStep/SouceControlConfiguration/index.tsx, frontend/src/hooks/useGetSourceControlConfigurationBranchEffect.tsx, frontend/src/hooks/useGetSourceControlConfigurationCrewEffect.tsx, frontend/src/hooks/useGetSourceControlConfigurationRepoEffect.tsx
...
_Description_
_Description_
_Null_
=> ADM-999 [frontend][backend]: fix the error path
